### ISSUE TITLE
Stress Screen Blur

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#100]
#### __Description__ 
Was stressed, ate many items to help relieve it, stress bar is gone but I still have the blur several minutes afterwards

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(1290.941, -559.4894, 70.3001)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Fixed in `pre-alpha-1.14.0`
