### ISSUE TITLE
Bank accounts

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1002]
#### __Description__ 
Unable to withdraw money still from the created accounts. It says "Invalid amount" when I try to withdraw the money.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Artemis1290
**Coordinates** | vector3(-56.69919, -1752.437, 29.42101)
**Steam ID** | steam:1100001322df320
**Discord ID** | discord:364076542575247360
**Citizen ID** | MBL96415
**Character Name** | James Hardy

**Comment by BlueStorm324** [comment]
So I had $75 in the personal and $25,000 in the Savings. I withdrawed $75 from the savings and was able to, and deposited it into the personal. I then upped the amount that I wanted to pull from the "Savings" to $150 and was able to pull out $150. So I had to keep slowly increasing the amount that I could pull out by adding it to the personal.
