### ISSUE TITLE
underpaid off duty.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1006]
#### __Description__ 
Still getting paid $10 instead of $25 whilst off duty.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Artemis1290
**Coordinates** | vector3(-533.2573, -1213.607, 18.18485)
**Steam ID** | steam:1100001322df320
**Discord ID** | discord:364076542575247360
**Citizen ID** | HFB40197
**Character Name** | Andrew Castle

**Comment by Dimmies** [comment]
Duplicate of #986
