### ISSUE TITLE
Nitrus / fake plates broken

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1008]
#### __Description__ 
No menu option pops up when in the spot to buy nitrus or fake plates
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cosmic
**Coordinates** | vector3(1207.619, -3114.273, 5.540318)
**Steam ID** | steam:11000010e00ec05
**Discord ID** | discord:534521268792197120
**Citizen ID** | ZDT28872
**Character Name** | Alex Camorra

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
