### ISSUE TITLE
Hair Changes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1009]
#### __Description__ 
Logged in and hair was the same odd style as when the clothing addition change was made. Went through the different hair styles and 3/4 or more were the same. The styles would not change through the number rotation.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-278.1091, 6228.5, 31.69378)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
It seemed to work a bit more in reverse but still not as it should. This seems to be similar to the clothing bug.

**Comment by eamundson1** [comment]
Typing in a number did not change anything btw.
