### ISSUE TITLE
Cooldown for Doorbell

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#101]
#### __Description__ 
When you ring a doorbell, start a cooldown of a few seconds before allowing them to ring it again
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(1301.746, -569.0733, 71.49868)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Added in `pre-alpha-1.14.0`
