### ISSUE TITLE
Clothing Revert

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1015]
#### __Description__ 
You can not revert clothing (i.e. clients can only go backwards via clothing menu, and not forward) - also not displaying numbers. There is a client error.
#### __Evidence__ 
https://imgur.com/fTl5nmq
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | hnt-neptunium
**Coordinates** | vector3(459.576, -996.8413, 30.68959)
**Steam ID** | steam:1100001441b0eb2
**Discord ID** | discord:333624300042977280
**Citizen ID** | BRJ62199
**Character Name** | Douth Chaney

**Comment by ghost** [comment]
merge

#1014 #1012 #1010

**Comment by ghost** [comment]
i can take a look at this when you're available
