### ISSUE TITLE
garage bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1016]
#### __Description__ 
i just pulled out my blazer and it popped my tires and engine got stalled again
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | cheezy
**Coordinates** | vector3(1737.596, 3721.406, 33.27808)
**Steam ID** | steam:11000010220bca1
**Discord ID** | discord:547819740811362367
**Citizen ID** | BTI80844
**Character Name** | Max Teller

**Comment by Dimmies** [comment]
Duplicate of #976
