### ISSUE TITLE
garage glitch

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1017]
#### __Description__ 
just pulled out my deviant and it popped tires and engine stalled

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | cheezy
**Coordinates** | vector3(1737.589, 3721.391, 33.43652)
**Steam ID** | steam:11000010220bca1
**Discord ID** | discord:547819740811362367
**Citizen ID** | BTI80844
**Character Name** | Max Teller

**Comment by Dimmies** [comment]
Duplicate of #976
