### ISSUE TITLE
House Garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#102]
#### __Description__ 
House garages were placed, however there is no prompt showing for the garage
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(1296.867, -563.3266, 70.87283)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Seems to fix itself when the script is restarted.

**Comment by Dimmies** [comment]
Fixed in `pre-alpha-1.14.0`
