### ISSUE TITLE
Removing Clothes From Body With Command

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1021]
#### __Description__ 
/shirt removes the t-shirt as well, so if you have a pocket flag in the t-shirt category and type /shirt, it removes your top and also any t-shirt clothing you have on (vests, holsters, ties etc).
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Curtis
**Coordinates** | vector3(1310.44, -1661.088, 51.23623)
**Steam ID** | steam:1100001116d7bcc
**Discord ID** | discord:360933761849884674
**Citizen ID** | JWG03022
**Character Name** | Santiago DeLeon

**Comment by Dimmies** [comment]
Alternative pocket flags can be found in Bags/Necklaces/etc.
