### ISSUE TITLE
Vehicle Persistence is fucked

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#103]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(1299.779, -568.8958, 71.68898)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Vehicle Mods aren't saving, cars vanishing?

**Comment by Dimmies** [comment]
Vehicle mods not saving should be fixed with `pre-alpha-1.14.0` - I'll keep this issue open until it's confirmed to be fully resolved
