### ISSUE TITLE
EMS Maverik bugs

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1034]
#### __Description__ 
The fourth seat in the maverick cant be entered manually and if put into the seat from the outside it looks really strange. 
#### __Evidence__ 
https://medal.tv/games/gta-v/clips/5CxcY7IaFaBvv/d1337xSCFRVN?invite=cr-MSw4dXEsMjQ5MDczMTgs
https://medal.tv/games/gta-v/clips/5CwIRFI_wB5nd/d1337ep4iSoO?invite=cr-MSxTdnUsMjQ5MDczMTgs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(-1794.8, -1222.784, 0.3484094)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by Dimmies** [comment]
Fixed in next update
