### ISSUE TITLE
Paleto has no locks

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1039]
#### __Description__ 
The Paleto PD has no lock and you can walk straight to armoury as a civ.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JohnnyCache
**Coordinates** | vector3(-445.8555, 6008.181, 36.99568)
**Steam ID** | steam:1100001034cbff2
**Discord ID** | discord:101373597708210176
**Citizen ID** | XQX05491
**Character Name** | Barry Shimshek

**Comment by Dimmies** [comment]
Not a bug
