### ISSUE TITLE
/mdt command not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1044]
#### __Description__ 
/mdt command not working on LEO. Keybind still works, just not the chat command.
#### __Evidence__ 
n/a
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuzible
**Coordinates** | vector3(441.5421, -986.8019, 34.97025)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | UKD42498
**Character Name** | Adam Hall

**Comment by Dimmies** [comment]
The MDT command changed to `/pdmdt`

You can you the F1 radial menu or the delete key to quickly open the MDT.
