### ISSUE TITLE
/mdt not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1045]
#### __Description__ 
Try typing in mdt and its now working for SD
#### __Evidence__ 
https://www.youtube.com/watch?v=UrkZWydljAA&ab_channel=xlt588gaming
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Adam Garcia
**Coordinates** | vector3(309.2276, -586.577, 43.28405)
**Steam ID** | steam:110000106516f33
**Discord ID** | discord:151138481068965888
**Citizen ID** | AST37015
**Character Name** | Adam Garcia

**Comment by Dimmies** [comment]
The MDT command changed to `/pdmdt`

You can you the F1 radial menu or the delete key to quickly open the MDT.
