### ISSUE TITLE
Fuel pumps don't read vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1048]
#### __Description__ 
Went to several gas station and tried different sides of vehicle(winky) and different positions and would get "not close enough" warning. Will attach screenshots.

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-723.2141, -932.1335, 19.21393)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2695971233

**Comment by eamundson1** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2695971846
