### ISSUE TITLE
Can't retrieve vehicles from house garages

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#105]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(284.1541, -650.3651, 42.01866)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Fixed in `pre-alpha-1.14.0`
