### ISSUE TITLE
Character creation Busted

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1050]
#### __Description__ 
Eddie told me that the arrows(sliders) to choose the different features was not working and the only way to choose is to put the number in. I then entered the server and sttempted to make a character. I found that the arrow selectors did not work properly.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-47.49778, -654.3928, -56.92727)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
I did not see any errors however in F8 I saw the last 3 entries were concerning marijuana 0 out of 20 plants.
