### ISSUE TITLE
UI elements

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1051]
#### __Description__ 
Optimize UI elements to scale appropriately on different resolutions (other than 1920x1080)
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuzible
**Coordinates** | vector3(437.3833, -983.3344, 30.68958)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | UKD42498
**Character Name** | Adam Hall

**Comment by Dimmies** [comment]
Duplicate of #883
