### ISSUE TITLE
Character Hair

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1053]
#### __Description__ 
Character is spawning with different hair
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2698320281

https://steamcommunity.com/sharedfiles/filedetails/?id=2698321073
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(195.17, -933.77, 30.69179)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
The hair is the same hair that appeared when the new clothing was introduced. This is an intermittent, ongoing issue.

**Comment by eamundson1** [comment]
I should add that more than 50% of the time I am unable to see the ped when spawning in and selecting the character or parts of the ped will be invisible.
