### ISSUE TITLE
Stress effects don't punish enough.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#106]
#### __Description__ 
You can have 100% stress and still have 0 issues playing
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(-353.8629, -55.2898, 49.0366)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Doing things that remove large amounts of stress should also add some "stress satiation".

Ex: If you drink a shake, it should reduce the amount of stress received by x amount for x minutes

**Comment by Dimmies** [comment]
Added to todo list, will look into later
