### ISSUE TITLE
Weed Harvesting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1067]
#### __Description__ 
I am unable to harvest some of my plants that are at 100% and still have some food and water too
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | StevenBillls
**Coordinates** | vector3(339.3869, 6458.345, 30.29685)
**Steam ID** | steam:11000013bedcecb
**Discord ID** | discord:501585887096864788
**Citizen ID** | PVF94604
**Character Name** | Ricky Barnes

**Comment by Dimmies** [comment]
Duplicate of #1068
