### ISSUE TITLE
Cannot Change Voice Range

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1069]
#### __Description__ 
Some time ago I noticed that F11 does not change the voice range (whisper, normal, yell) I also do not have an option to set a key to control voice.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1978.889, -526.9933, 11.87544)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Settings > Key Bindings > FiveM > Cycle Proximity
