### ISSUE TITLE
Gas canister / overweight

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1070]
#### __Description__ 
If you have too much weight and try to buy a gas canister, you'll be charged the $50 but not receive the cannister due to being overweight
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Punisherinokc
**Coordinates** | vector3(2679.424, 3266.682, 55.24057)
**Steam ID** | steam:11000013560a956
**Discord ID** | discord:483737482463150080
**Citizen ID** | WCF84839
**Character Name** | Billy Blue

**Comment by Dimmies** [comment]
The canister would drop on the ground (probably is dropping inside of the actual pump)
