### ISSUE TITLE
Boilingbroke Prison Locks

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1075]
#### __Description__ 
All locks need to be reworked, inmates have access to catwalk, guard towers, etc.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuzible
**Coordinates** | vector3(1815.259, 2620.012, 54.27981)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | UKD42498
**Character Name** | Adam Hall

**Comment by Dimmies** [comment]
Catwalks still need locks
