### ISSUE TITLE
Fake Plates Not Sticking

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1080]
#### __Description__ 
I applied fake plates before a race, did the race and then had to use the phone tracker to find my car again after I had to ditch it. When I recovered it at the last location it was at (where I applied the fake plates), I reapplied new fake plates so that there would be fakes on the vehicle. Cops still somehow managed to get a plate read on my vehicle which is the reason they were able to issue a warrant for my arrest.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cloverism
**Coordinates** | vector3(148.2052, -3028.106, 7.040886)
**Steam ID** | steam:1100001082ad5b9
**Discord ID** | discord:520646426951155714
**Citizen ID** | AEF88850
**Character Name** | Margo Gray

**Comment by Dimmies** [comment]
Not a bug, fake plates need a heavy rehaul though
