### ISSUE TITLE
Prison jobs not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1081]
#### __Description__ 
Prison jobs not working - Everytime i get a job he says he never gave me one once i do it.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | ByKaz
**Coordinates** | vector3(1830.526, 2585.294, 46.01431)
**Steam ID** | steam:1100001425b0aae
**Discord ID** | discord:762374874470809600
**Citizen ID** | YPO12927
**Character Name** | Ky Romero

**Comment by Dimmies** [comment]
No other reports of this or similar.
