### ISSUE TITLE
Hitting G while down failed to notify EMS

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1088]
#### __Description__ 
I was hit byu a local car and got downed, when I hit G nothing came up to say EMS were alerted, the option to contact EMS is now gone, looking in F8 I don't see where the button was activated to alert EMS
#### __Evidence__ 
https://imgur.com/a/0UPCdbK
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Huggle
**Coordinates** | vector3(886.3355, -995.3683, 32.42831)
**Steam ID** | steam:110000105e15e8d
**Discord ID** | discord:176357089705328640
**Citizen ID** | WKR02823
**Character Name** | Roland Archer

**Comment by Dimmies** [comment]
Intended so not a bug, but I've added a notification to let you know that EMS have been notified
