### ISSUE TITLE
Boss Menu Firing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1097]
#### __Description__ 
Still not working
#### __Evidence__ 
https://i.imgur.com/F478fXH.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuzible
**Coordinates** | vector3(456.2926, -987.1942, 30.68959)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | UKD42498
**Character Name** | Adam Hall

**Comment by zeuzible** [comment]
https://medal.tv/games/gta-v/clips/7J8OSeggbR5v8/d1337pfCYx77?invite=cr-MSxxOFYsMjU1MjYxMDYs
