### ISSUE TITLE
Scenes still there after the storm

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1099]
#### __Description__ 
scene at Hayes auto is still on the wall after the storm
#### __Evidence__ 
https://i.imgur.com/82RTWwr.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dopykoh
**Coordinates** | vector3(-1425.678, -441.0329, 35.85886)
**Steam ID** | steam:11000011376e182
**Discord ID** | discord:193681533620584448
**Citizen ID** | VJG97234
**Character Name** | Jose Fernandez

**Comment by Dimmies** [comment]
Not a bug, you can set durations for scenes
