### ISSUE TITLE
Fingerprint IDs aren't working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#11]
#### __Description__ 
Might just need a full rewrite at this point

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(30.24493, -1352.305, 29.34146)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
See #9
