### ISSUE TITLE
fish vendor is not marked on the map

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#110]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-1667.644, -974.324, 7.484435)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.14.0`
