### ISSUE TITLE
Vehicle not starting/Getting in through closed door

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1101]
#### __Description__ 
When i try to get into my vehicle, i do the open animation like im opening the door and getting in but the door actually doesnt open and i still get in and the vehicle keeps trying but wont turn over.
#### __Evidence__ 
https://medal.tv/games/gta-v/clips/7xRvitVioli9Z/d1337g53Wagj?invite=cr-MSx4VFQsNDE1MzI3Mjcs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Beans
**Coordinates** | vector3(316.5544, -2032.668, 20.56001)
**Steam ID** | steam:11000010e9a5264
**Discord ID** | discord:249800125587652608
**Citizen ID** | ZGH99893
**Character Name** | Andy Doyle

**Comment by Dimmies** [comment]
Clip no longer exists
