### ISSUE TITLE
Rouge Saved Outfits

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1104]
#### __Description__ 
I woke and all of my saved outfits are completely different. A few with no arms or torso(which I woke up in the lobby like). I've tried restarting with no success
#### __Evidence__ 
https://imgur.com/a/vtcUPrn
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Jickle Mithers
**Coordinates** | vector3(-47.83081, -654.3427, -56.92729)
**Steam ID** | steam:110000104657b9a
**Discord ID** | discord:245049156912152576
**Citizen ID** | LRC92124
**Character Name** | Jickle Mithers

**Comment by Dimmies** [comment]
The outfits were likely created before we had our big clothing update, you'll need to remake them
