### ISSUE TITLE
Cocaine chemical runs

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1106]
#### __Description__ 
Just about every other time we do a chemical run.. when we get the van from the cartel and bring it back to the guy at the dock to unload the chemicals.. the truck seems to be bugged out. It wont give the option half the time.. so we waste a lot of time with the whole process and cant get our chemicals. From now on I will make sure to clip this so it can be reviewed.. but about 5 out of 10 times now its happened and we dont receive our chemicals
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Caino13
**Coordinates** | vector3(279.2176, -647.0665, 42.0186)
**Steam ID** | steam:1100001092c5fd0
**Discord ID** | discord:383844813218381824
**Citizen ID** | MTR54389
**Character Name** | Mike Samsonite

**Comment by Dimmies** [comment]
The person who gets the job, has to turn the truck in.
I've added some more error handling to try and give you guys a better idea of why it wont return. Video would be helpful!
