### ISSUE TITLE
Car stuck

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1107]
#### __Description__ 
Car moves a bit then gets stuck. This is a vehicle from the welcome gift.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ascending Gamer
**Coordinates** | vector3(228.8547, -804.5468, 30.35953)
**Steam ID** | steam:11000010cfc26ee
**Discord ID** | discord:302912403979370497
**Citizen ID** | CKJ13959
**Character Name** | Jake Guzik

**Comment by Dimmies** [comment]
Likely due to speed limiter. Try hitting B
Could also be gas, so check fuel.
