### ISSUE TITLE
fish vendor does not work

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#111]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-1668.363, -976.3129, 7.433009)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.14.0`
