### ISSUE TITLE
Casino Chip Issue

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1113]
#### __Description__ 
Bought 2000 chips at the casino. Went to pay roulette and it said I had no chips. Went back to the lady and it said I still had 2000 chips. Storm hit, and all my chips were gone. Did it again for the video, same issue.  
#### __Evidence__ 
https://drive.google.com/file/d/1fUYxbJ6kuZAvkfeLTlIzFTt_F2FuzsfS/view?usp=sharing
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Punisherinokc
**Coordinates** | vector3(128.8426, -3015.079, 10.70344)
**Steam ID** | steam:11000013560a956
**Discord ID** | discord:483737482463150080
**Citizen ID** | WCF84839
**Character Name** | Billy Blue

**Comment by douth-c-archive** [comment]
Seems to have been resolved via latest changelogs, can be closed.
