### ISSUE TITLE
Notepad

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1116]
#### __Description__ 
Don't know if it is a bug however the notepad is a one-use item instead of multiple uses like it used to be.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-75.3524, -654.7263, -56.97389)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Intended
