### ISSUE TITLE
PlasmaGame Outfits

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1121]
#### __Description__ 
PlasmaGame was affected by the outfit updates, making it so you don't wear the full team outfit any longer and have no arms.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Casso
**Coordinates** | vector3(-1089.595, 4277.12, 95.51807)
**Steam ID** | steam:1100001037a1b0f
**Discord ID** | discord:188065178426933249
**Citizen ID** | ZIF94758
**Character Name** | Kieron Casso

**Comment by douth-c-archive** [comment]
Can confirm, +1. Clothing updates that include or remove old/new items will mess with config.
