### ISSUE TITLE
No payment notification

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1122]
#### __Description__ 
When payment is received no notification is received. The only way is to check through an atm or to know exactly how much money you have. This started a couple days ago. Others have the same problem
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1410.869, -432.5939, 35.69998)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
That is payment that is sent to you, not cash.
