### ISSUE TITLE
Hair

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1129]
#### __Description__ 
When logging in the hair is set to a hair style not, previously, chosen.

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(490.5167, 5702.398, 727.8527)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Duplicate of #630
