### ISSUE TITLE
Bank transfer

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1133]
#### __Description__ 
Tried to bank transfer to a friend using the account provided by his phone number, Cash came out of my account but was never received on his end.
#### __Evidence__ 
Sent a picture of Outgoing transfer in discord
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | John Reynold
**Coordinates** | vector3(151.7745, -1038.873, 29.3681)
**Steam ID** | steam:11000010aa655e0
**Discord ID** | discord:473289286398246924
**Citizen ID** | DOT66423
**Character Name** | John Reynold

**Comment by douth-c-archive** [comment]
Similar, https://github.com/TheHiveRP/HiveIssues/issues/1150

**Comment by douth-c-archive** [comment]
I believe this has been resolved anyways.
