### ISSUE TITLE
Vehicle violently whipping around and killed me

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1134]
#### __Description__ 
as title states, entered a vehicle and it started violently whipping around and killed me. Have had this problem in a previous state and do not have evidence from this incident but have previous recording of exact thing happening.
#### __Evidence__ 
https://clips.twitch.tv/SullenSingleButterOSfrog-sstDVRpF3vlC6PPX
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | John Reynold
**Coordinates** | vector3(-113.9113, -1130.132, 25.69433)
**Steam ID** | steam:11000010aa655e0
**Discord ID** | discord:473289286398246924
**Citizen ID** | DOT66423
**Character Name** | John Reynold

**Comment by douth-c-archive** [comment]
merge https://github.com/TheHiveRP/HiveIssues/issues/1136
