### ISSUE TITLE
Mystery prize on casino wheel gave $0

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1135]
#### __Description__ 
Spun the wheel during daily spins and got a mystery prize which was $0
I'm not mad, just not sure if that's supposed to be a possible prize
#### __Evidence__ 
http://prntscr.com/26fd0s0
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Huggle
**Coordinates** | vector3(975.9039, 47.59205, 74.67618)
**Steam ID** | steam:110000105e15e8d
**Discord ID** | discord:176357089705328640
**Citizen ID** | WKR02823
**Character Name** | Roland Archer

**Comment by Dimmies** [comment]
You got a RC Car, not money.
