### ISSUE TITLE
INVOLUNTARY MOVEMENT/TORNADO VEHICLE

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1136]
#### __Description__ 
unable to control movement if placed in vehicle vehicle flys out of control
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | .βŁΔCKDЯΔĢØN.[LDR]
**Coordinates** | vector3(301.5773, -620.1983, 43.4494)
**Steam ID** | steam:1100001423fa64c
**Discord ID** | discord:281904406155231233
**Citizen ID** | MJB05265
**Character Name** | Richard Bolzaak

**Comment by douth-c-archive** [comment]
- This can be resolved by using "propfix" client command. Could be added to detect tornado and suggest the usage?
