### ISSUE TITLE
Unable to see persons MDT report

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1144]
#### __Description__ 
It seems, whenever we try to see Robert O'Neils MDT file it refuses to open. I would imagine it's the comma in his name.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Sayahchan
**Coordinates** | vector3(313.6378, -590.4942, 43.28409)
**Steam ID** | steam:11000010413aae1
**Discord ID** | discord:397959613061791745
**Citizen ID** | FFU45850
**Character Name** | Charlene Garcia

**Comment by douth-c-archive** [comment]
This has been resolved and can be closed. Character name changed to remove the " ' ".
