### ISSUE TITLE
35 k not moved to bank

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1150]
#### __Description__ 
Money given via paypal shows on transfer list but not represented in bank statment total missing is 35,000
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | pwmderheim
**Coordinates** | vector3(-33.65373, -1100.007, 27.27436)
**Steam ID** | steam:110000145c6aa26
**Discord ID** | discord:418843816494104577
**Citizen ID** | CYO64960
**Character Name** | Toni Paterson

**Comment by douth-c-archive** [comment]
This would need to be a comp request. I believe this is a known bug is is fixed/will be fixed.
