### ISSUE TITLE
Intergrity Aps dissappear while in elevator.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1174]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TobyOllmaen
**Coordinates** | vector3(284.537, -654.3464, 42.01796)
**Steam ID** | steam:110000139d95da8
**Discord ID** | discord:362562882493218816
**Citizen ID** | KPY20971
**Character Name** | Toby Ollmaen

**Comment by Dimmies** [comment]
Lack of information
