### ISSUE TITLE
Apartments

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1176]
#### __Description__ 
Walking into an apt, where another person is, currently is still bugged.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-313.3984, -655.9225, -56.97388)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Duplicate of #562
