### ISSUE TITLE
Deleted item doesn't delete

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1179]
#### __Description__ 
Decorating a house and deleted item isn't disappearing. I'm also still able to craft with it despite it being deleted and unable to be moved. 
#### __Evidence__ 
https://i.ibb.co/2Z2h1wz/image.png
https://i.ibb.co/fq7chy5/image.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel.ttv
**Coordinates** | vector3(298.0533, -1981.289, -0.9494091)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment]
Similar to #980 - Assuming it's the same bug
