### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1191]
#### __Description__ 
Cannot get out of emotes. X will not stop it and ragdoll does nothing either. There is an error attached.
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2750549610
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1395.043, -419.8019, 37.85885)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
Others are also encountering this.
