### ISSUE TITLE
Characters Hair style

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1199]
#### __Description__ 
I have saved and saved new outfits with my hair choices multiple times however when i get back into city my hair reverts to being bald or something totaly different. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | EDMDillon
**Coordinates** | vector3(163.9475, -653.7259, -56.97388)
**Steam ID** | steam:110000109ef001b
**Discord ID** | discord:822250202479853568
**Citizen ID** | ALN44792
**Character Name** | Scarlet Shepard

**Comment by Dimmies** [comment]
Duplicate of #630
