### ISSUE TITLE
Tint not sticking

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1204]
#### __Description__ 
Ubermacht Sentinerl Sg4. I put tint on the car Friday but he tint is no longer on it and will not ;let me put it on it. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1417.297, -446.3913, 35.56723)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2752033997   for tag. Not my car.
