### ISSUE TITLE
ATMs

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1215]
#### __Description__ 
Some ATMs mounted on the wall work for some players and not others
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuzible
**Coordinates** | vector3(-815.3044, -1084.034, 10.37425)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
You'll need to look at these in a specific area, the keypad usually does the trick for me.
