### ISSUE TITLE
Fake plate

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1226]
#### __Description__ 
After you put a fake plate on your car your items in the glovebox get deleted.
#### __Evidence__ 
I have nothing as my shadow play was disabled, I lost a nos bottle and a pickaxe though. (its ok if i dont get it back i get i didnt have proof)
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Jessup <3
**Coordinates** | vector3(32.06519, -1030.361, 28.86736)
**Steam ID** | steam:110000147da5b40
**Discord ID** | discord:628711847784349712
**Citizen ID** | PEG38652
**Character Name** | Jessup Baker

**Comment by Dimmies** [comment]
These are known issues (unfortunately)
Technically a bug, but it was known while creating the fake plate system. Fake plates need a heavy rehaul.
