### ISSUE TITLE
/mdt Command

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1235]
#### __Description__ 
/mdt command still not working sadge
#### __Evidence__ 
No F8 errors
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuzible
**Coordinates** | vector3(460.533, -985.3188, 30.72808)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | UKD42498
**Character Name** | Adam Hall

**Comment by Dimmies** [comment]
Police MDT Command is /pdmdt
