### ISSUE TITLE
Trunks

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1239]
#### __Description__ 
using f2 isnt working for some reason
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | AJ Bakaro
**Coordinates** | vector3(240.6469, -808.5256, 30.26773)
**Steam ID** | steam:11000010d39555d
**Discord ID** | discord:105865479226171392
**Citizen ID** | ZLF37761
**Character Name** | AJ Bakaro

**Comment by Dimmies** [comment]
Not enough info
