### ISSUE TITLE
Can't Stack Cigs

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1244]
#### __Description__ 
When buying smokes from the store, it only let me buy one at a time. It also wouldn't let me stack them in my pockets. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Vespaer
**Coordinates** | vector3(1136.73, -981.3497, 46.4158)
**Steam ID** | steam:11000011a4b3032
**Discord ID** | discord:299363685925650442
**Citizen ID** | JKC99143
**Character Name** | Marlee Kingsley

**Comment by Dimmies** [comment]
Duplicate of #1243
