### ISSUE TITLE
Pops Biz can't craft

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1246]
#### __Description__ 
Can not craft at pops biz - clocked in, tried having bulk items in inventory and then just 1 of each item needed. Getting message "You don't have the right items" 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel.ttv
**Coordinates** | vector3(224.1549, -790.6373, 30.86637)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment]
Related to #1247
