### ISSUE TITLE
Wheels Changed at Random

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1267]
#### __Description__ 
My rims and wheels changed out of nowhere
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | SkiTheArmyGuy
**Coordinates** | vector3(-30.43012, -1054.822, 27.83533)
**Steam ID** | steam:11000010693e7cb
**Discord ID** | discord:916380346336038932
**Citizen ID** | SQO97343
**Character Name** | Kazica Bushida

**Comment by Dimmies** [comment]
Duplicate of #1183
