### ISSUE TITLE
Tuner Cars

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#128]
#### __Description__ 
Not sure if this was intended as we plan on making Tuner Cars an update release, but we can not spawn the tuner update vehicles from GTA at all
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-189.0257, -1301.588, 31.29649)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Tuner cars will come in a later update, it was intended for them to be left out
