### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1286]
#### __Description__ 
At the quarry mining.. mined about 10 different rocks and went to load them in the van and nothing is in my inventory. Showed that I mined different material but it never ended up in my inventory.. never had this issue and medal.tv is down for me so wouldnt let me clip it.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Caino13
**Coordinates** | vector3(2995.189, 2770.722, 42.79968)
**Steam ID** | steam:1100001092c5fd0
**Discord ID** | discord:383844813218381824
**Citizen ID** | MTR54389
**Character Name** | Mike Samsonite

**Comment by Dimmies** [comment]
Should be resolved as of [1.85.0](https://hiverp.net/changelogs)
