### ISSUE TITLE
cant check in while down 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#129]
#### __Description__ 
cant check in while down 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | photog0510
**Coordinates** | vector3(442.274, -989.2629, 25.70045)
**Steam ID** | steam:11000013e0a6e14
**Discord ID** | discord:521065052904882189
**Citizen ID** | HMU11415
**Character Name** | Chris Jones

**Comment by Dimmies** [comment]
Have to lay in the bed directly (have someone carry you to the bed in the back)
