### ISSUE TITLE
Garbage truck crash

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1298]
#### __Description__ 
If you attempt to get into a garbage truck "trunk" via the LALT menu, it will crash your game. You may need to have the garbage truck job or have a garbage bag in your hand from the job.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(484.8624, -1031.354, 34.66089)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | PNG50237
**Character Name** | James Wildin

**Comment by Dimmies** [comment]
Duplicate of #543
