### ISSUE TITLE
Bank Trucks are free money

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1299]
#### __Description__ 
Bank trucks are scuffed and not manned so people just pull open the door and drive off with them with them.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(962.566, 88.24741, 80.89055)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
Also are unlocked
