### ISSUE TITLE
Mine Scuffed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1310]
#### __Description__ 
No materials are gained from mining or so I am told.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1412.313, -449.4144, 35.90971)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
I just tested it and received ore. So either fixed from restart(no idea if they did it before or after restart) or it might be a problem with certain people.

**Comment by eamundson1** [comment]
I was using a normal pickaxe btw.
