### ISSUE TITLE
Prize Wheel

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1314]
#### __Description__ 
Took $500 and did not spin. No error message.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(975.7545, 49.8206, 74.68112)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
It seems this bug is known to people. I paid twice and had no spin. It also displayed no results. However when someone else spins, you then get the money. It still did not display the results.

**Comment by Dimmies** [comment]
Duplicate of #619
