### ISSUE TITLE
Can't "pack" the meth pipe

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1319]
#### __Description__ 
Combining Meth and Glass Pipe won't craft Meth Pipes
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Administries
**Coordinates** | vector3(1754.953, 2483.485, 45.7407)
**Steam ID** | steam:11000010b0b0a55
**Discord ID** | discord:154619574153641984
**Citizen ID** | ILT88962
**Character Name** | Eddie Russo

**Comment by Dimmies** [comment]
Duplicate of #1326
