### ISSUE TITLE
Female clothing for prison wrong

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1320]
#### __Description__ 
When sent to prison, loading in all I could see was a small yellow top, all of my torso and legs were gone and some high heels. I am a potato and can't figure out how to put the photos I took in this here bug report so I will try and go through the website and put them in that way. Just wanted to let you guys know female bodies are practically gone in prison. :P 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Vespaer
**Coordinates** | vector3(1383.867, -1541.776, 56.70988)
**Steam ID** | steam:11000011a4b3032
**Discord ID** | discord:299363685925650442
**Citizen ID** | FKX31546
**Character Name** | Raeya Calloway

**Comment by VespaerRae** [comment]
![image](https://user-images.githubusercontent.com/102325800/160000591-e57819b5-6a07-4d95-8de8-f8d015c4d851.png)

**Comment by VespaerRae** [comment]
![image](https://user-images.githubusercontent.com/102325800/160000659-d378eca8-c292-4907-8f93-e17b599710ec.png)
