### ISSUE TITLE
Graffiti Bugged

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1329]
#### __Description__ 
Cannot bring up a cursor to select options. Also cannot exit graffiti. No F8 errors.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(30.87925, -1742.717, 29.3037)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
When I enter a vehicle it is as if I have no clipping on. Also the starter keeps going and vehicle won't turn on. have to exit game to clear Graffiti.

**Comment by Dimmies** [comment]
This is not a bug, you have to hit G to toggle your cursor
