### ISSUE TITLE
Car boosting 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1333]
#### __Description__ 
I reccieved a contract to boost a blista. I was with a buddy who dropped me off at a garage so i could pull out my car and pick him up from a boost he aws dropping off. The car i pulled out of my garage was a Blista. I noticed the blue circle i had on my map dissapeared when i got in. Wasn't sure what to do so i cancelled my boost and my own personal blista dissapeared. 
#### __Evidence__ 
Sorry i didn't capture any screenshots. 
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | mettem27
**Coordinates** | vector3(1166.908, -1654.825, 36.77851)
**Steam ID** | steam:11000010a10ec6d
**Discord ID** | discord:176543281767776257
**Citizen ID** | OAG07996
**Character Name** | Quinton Fox

**Comment by Dimmies** [comment]
Unable to replicate after multiple attempts along with no other complaints similar to this. Closing
