### ISSUE TITLE
suv's spawn under the floor

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#134]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-49.97619, -1096.372, 26.42699)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Merge #135

**Comment by Dimmies** [comment]
Merge #140

**Comment by Dimmies** [comment]
New PDM script fixes all of this
