### ISSUE TITLE
Murderous Motorcycle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1347]
#### __Description__ 
Diabolus motorcycle launched me into the air multiple times, resulting in $800 worth of pillbox bills, and flipping bike, causing damage of roughly $1200.  Finally fixed by unflipping bike and pushing to Benny's.  Not wearing any clothing out of the usual, never had collision problems before.  Happened outside PDM after parking in front lot and test driving a few vans.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | ThatPirateGuy
**Coordinates** | vector3(1202.262, 2714.052, 38.22258)
**Steam ID** | steam:11000010360f509
**Discord ID** | discord:277579665764515851
**Citizen ID** | HBF84198
**Character Name** | Lucas Madrano

**Comment by eamundson1** [comment]
I had a similar situation a couple of days ago after looking at vans. I assumed, at the time, it was because I had a pickaxe on my back..
