### ISSUE TITLE
horns

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1353]
#### __Description__ 
horns work for most cars but the sunrise doesn't, some selections just sound like a normal horn
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | dovesi
**Coordinates** | vector3(-1420.465, -453.5102, 35.90971)
**Steam ID** | steam:11000010569bde9
**Discord ID** | discord:126185398345924609
**Citizen ID** | JVG50155
**Character Name** | Dove Daniels

**Comment by Dimmies** [comment]
Duplicate of #1223
