### ISSUE TITLE
lifting fingerprint

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1362]
#### __Description__ 
I did the lift fingerprint off of a vehicle, it did not give me a successfull or failed prompt. When I went to MRPD to analize it I had nothing to analize. I had empty evidence bags in my inventory
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(474.209, -986.9937, 30.69087)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | GHH64203
**Character Name** | Mason Saint

**Comment by Dimmies** [comment]
Not a bug, there just was no fingerprints on the vehicle
