### ISSUE TITLE
Hair problem and SMG on back

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1369]
#### __Description__ 
Same hair problem but now with a smg on the back. I didn't notice the smg until after I changed the hair.

#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2792108374
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-278.8282, 6228.691, 31.69551)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
There is no smg in character inventory. None of my characters have an smg btw.
