### ISSUE TITLE
Football

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1372]
#### __Description__ 
Maybe it isn't a bug however I cannot remove it from my hand and store it in inventory.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1411.952, -431.5846, 36.21107)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Not a bug, you need to throw it and pick it up with third eye.
