### ISSUE TITLE
Bank Truck

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1374]
#### __Description__ 
Bank truck with no personnel and parked along road. No signs of any damage.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1320.64, -841.2101, 16.97779)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
Truck was locked.
https://steamcommunity.com/sharedfiles/filedetails/?id=2793529441
https://steamcommunity.com/sharedfiles/filedetails/?id=2793529764

**Comment by eamundson1** [comment]
fOUND A SECOND TRUCK IN SAME SPOT
