### ISSUE TITLE
Tattoos

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#138]
#### __Description__ 
Where my tattoos at baby???
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-36.8509, -1109.424, 26.43701)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
They'll be in after alpha probably (low prio right now)
