### ISSUE TITLE
PDM Catalog

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#139]
#### __Description__ 
This isnt a bug, its a suggestion. It would be nice to have a catalog so people know what vehicles are available. If we can buy cars without a salesman, you can only buy the ones on the showroom floor, non car dealers can not change the display vehicles

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-46.76959, -1097.594, 26.42699)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Players can change the showroom floor if there are no car dealers online.
