### ISSUE TITLE
custom plate issue

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1392]
#### __Description__ 
when my plate was applied, it wiped by trunks inventory 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | iSpudnik
**Coordinates** | vector3(215.5026, -809.6912, 30.74034)
**Steam ID** | steam:11000010d45ec22
**Discord ID** | discord:128931365675728896
**Citizen ID** | XLP22750
**Character Name** | Nazario Rossi

**Comment by eamundson1** [comment]
I comped the the items.
