### ISSUE TITLE
Money Trucks

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1393]
#### __Description__ 
Been seeing Money trucks just parked around the city and never being drove by the locals inside them. Makes it super easy to take these.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chromello
**Coordinates** | vector3(-126.1284, -326.1308, 37.43839)
**Steam ID** | steam:1100001129a3cb2
**Discord ID** | discord:203011726457831425
**Citizen ID** | CDY47707
**Character Name** | Charles Patrone

**Comment by eamundson1** [comment]
Saw three empty ones at the spawn on Great Ocean and then one, occupied, truck drive from there. Also saw 1 truck, in the wrong, lane by Hayes. It was not occupied.

**Comment by eamundson1** [comment]
They cannot be DV'd by any manner now or impounded.
