### ISSUE TITLE
Meth Grab Ingredient Polylooks not working on start.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#14]
#### __Description__ 
Have to restart to get it to work
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(1992.768, 4964.599, 31.35526)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
Added waiting until hive-interact is loaded. This *should* solve the issue. Needs testing though

**Comment by Dimmies** [comment]
> Added waiting until hive-interact is loaded. This _should_ solve the issue. Needs testing though

Didn't fix the issue, needs more work

**Comment by Dimmies** [comment]
Fixed with #68
