### ISSUE TITLE
Null Vehicle at PDM

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#141]
#### __Description__ 
In the OffRoad/Van Section, the Contender2 spawns as Null
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-218.6064, -1291.166, 31.20428)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Just took it out for now, not sure why it's showing as null
