### ISSUE TITLE
Farmer's Market

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1415]
#### __Description__ 
Doesn't buy milk, fruit, citris?
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cloverism.ttv
**Coordinates** | vector3(1902.865, 5132.057, 44.84344)
**Steam ID** | steam:1100001082ad5b9
**Discord ID** | discord:520646426951155714
**Citizen ID** | QXJ54743
**Character Name** | Nova Blake

**Comment by Dimmies** [comment]
Not intended to.. yet
