### ISSUE TITLE
Clothing Store

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#142]
#### __Description__ 
Cant see saved outfits in a clothing store, not sure if this is intentional

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(424.234, -808.0966, 29.49113)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Intentional. You'll have to go to your apartment or house, if you have one.
