### ISSUE TITLE
Scrap bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1421]
#### __Description__ 
says you are busy and then area already searched when it was never searched in the first place. Will attach F8
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(2350.46, 3064.627, 48.15237)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
https://steamuserimages-a.akamaihd.net/ugc/1841419337747460785/6E4238F6C04DD188FE69C58D61B8927A3D8935BA/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false
