### ISSUE TITLE
Issue with Wheel type

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1429]
#### __Description__ 
I crash when trying to look at the wheel types. all wheel types give me this issues i have recreated the problem mutiple times. the only thing in bennys i can not use at this moment. I recorded a short video so you can see the issue.
#### __Evidence__ 
https://youtu.be/TEDO7usqPfg 
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NaiyaBelle
**Coordinates** | vector3(195.1699, -933.7719, 30.69106)
**Steam ID** | steam:110000135fac924
**Discord ID** | discord:541452385936080966
**Citizen ID** | JDC92598
**Character Name** | Naiya Rossi

**Comment by Dimmies** [comment]
Fixed by clearing cache
