### ISSUE TITLE
Jerry Can

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#143]
#### __Description__ 
Cant purchase a jerry can at a gas station
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(1184.873, -329.117, 69.3142)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Merge #140

**Comment by Dimmies** [comment]
This was added
