### ISSUE TITLE
Nos noise not shutting off after use

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1431]
#### __Description__ 
After using Nos the spray audio continues even after being let go. As well as i found if you press it multiple times it will add to the audio making it SUPER loud.
#### __Evidence__ 
https://medal.tv/games/gta-v/clips/jvSKRpxdrgZVj/d1337tS3HMYS?invite=cr-MSw5TkYsMjU3NTAxOTcs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Britamins
**Coordinates** | vector3(105.8253, -1428.738, 28.73516)
**Steam ID** | steam:110000133272d55
**Discord ID** | discord:156579090315345920
**Citizen ID** | MHP48555
**Character Name** | Briten Clark

**Comment by Dimmies** [comment]
Disabled for now
