### ISSUE TITLE
Car Locks

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1433]
#### __Description__ 
Been experiencing car lock problems like the others. Doesn't matter with vehilce type. Will add F8 error
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1413.206, -432.7137, 36.11029)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
https://steamuserimages-a.akamaihd.net/ugc/1841419337747454290/E32E8F027001625D3953C96309D615137D72001F/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false
