### ISSUE TITLE
Up Arrow

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1446]
#### __Description__ 
I am unable to use my up arrow in bennys, to toggle selfie camera, or any ui screen
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | StevenBillls
**Coordinates** | vector3(1110.053, -2008.124, 31.0617)
**Steam ID** | steam:11000013bedcecb
**Discord ID** | discord:501585887096864788
**Citizen ID** | PVF94604
**Character Name** | Ricky Barnes

**Comment by Dimmies** [comment]
Make sure you keybind is set correctly.
`Key Bindings > Cellphone > Use Phone` should be Up Arrow.
