### ISSUE TITLE
Adverts

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1450]
#### __Description__ 
Adverts seem to stay up even when someone disconnects.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Lazrik
**Coordinates** | vector3(193.7662, -3166.973, 5.79027)
**Steam ID** | steam:1100001116d7bcc
**Discord ID** | discord:948810480535875604
**Citizen ID** | ZWP32858
**Character Name** | Curtis Prophet

**Comment by Dimmies** [comment]
Duplicate of #1445
