### ISSUE TITLE
House Robberies don't send police alert ?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#147]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(504.109, -1701.601, -12.92103)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
This is actually cause of a chance check
