### ISSUE TITLE
Bee Hive 2

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1473]
#### __Description__ 
Tried to place more bee hives down to replace the ones that broke however I get a message stating I may only have 5 bee hives. No other error messages.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(1547.154, 2246.636, 75.82699)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2805187575
