### ISSUE TITLE
Meth Cooking

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#15]
#### __Description__ 
Can put any ingrdients into the kelm, walk over to the prepare station, and get bags of 100 quality meth. Also, cant seem to drain or empty the kelm to restart a cook after an explosion
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(2013.323, 4983.104, 40.59358)
Steam ID | steam:11000011b56c5c4
Discord ID | discord:612497931169169408
Citizen ID | DXN74618

**Comment by Dimmies** [comment]
* You now have to do every step of the process before it allows you to prepare the meth
* The furnace now empties when you're finished processing the meth.
