### ISSUE TITLE
My house is NOT FOR SALE

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1503]
#### __Description__ 
I went to my house at Route 68 Approach and it is saying it is for sale for some reason. It will not let me in. I did not not put the house up for sale and my app says I still owen it.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-20.14464, 3030.508, 41.64562)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
Last night deputies did go in when I was down. However I went in, later last night with no problem and spawned there this morning.
I was able to no clip into it and exit normally, then it allowed me to enter as an owner and did not show for sale.
