### ISSUE TITLE
Cars duping

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1505]
#### __Description__ 
Picked up Joey Vaughns car on flatbead and noticed a dupe of his vehicle in it's spot. It is close to the arewa of the blinking police car. No errors
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-685.1393, -1105.059, 14.60966)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=280949569

**Comment by eamundson1** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2809495921
