### ISSUE TITLE
Casino-Roullete not paying out winnings twice

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1506]
#### __Description__ 
Hey all, I'm at the casino right now and I got screwed over twice. I didn't get the first one recorded which I'm actually really upset about because I put 4k on 00 and it actually hit, but I wasn't paying attention and saw it was on 00. I continued gambling and won/lose some here and there no issues, decided to throw another 1k on 00 and it hit but did the same thing. I snapped a recording of it, but I was on my other screen browsing Polo shirts on amazon (don't judge). So I have it set for 1 min and the beginning it shows me throw the 1k down, then i go to my other screen and then click back onto gta and its sitting on 00 just like the first time. But as you can see my money doesnt change. Any help? I've never hit a 00 before, let alone twice in one sitting and I'd really like to see if you guys can look back somehow in history/logs somewhere and see where I hit twice on it?
#### __Evidence__ 
https://medal.tv/games/gta-v/clips/lmikPNRz77TJh/d1337GkwQYe6?invite=cr-MSxTRVQsNTQ3Mzk1MTMs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | BeachNinjas
**Coordinates** | vector3(973.3853, 43.87428, 74.47629)
**Steam ID** | steam:110000101d1b1cd
**Discord ID** | discord:387047848031813643
**Citizen ID** | SZM57588
**Character Name** | Mike Williams

**Comment by BeachNinjas** [comment]
Hello =)
