### ISSUE TITLE
Can't get out of house

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1507]
#### __Description__ 
Logged in at house on 68 hwy and there is not option to exit.No error
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-15.001, 3030.468, 12.71379)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
Clipped out and house is acting like I don't own with no option to enter. It shows it is locked and g to press door bell.

**Comment by eamundson1** [comment]
I can still access everything inside of it.

**Comment by eamundson1** [comment]
Problem stopped when I relogged.
