### ISSUE TITLE
explosive mines

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1525]
#### __Description__ 
uable to use exlposive mines, only had dynamite and mining helmet if something more needed, used dynamite from invintory in single and stack, used dynamite with numbers in single and stacks, weraing and not wearing minig helmet
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Neuro Fission
**Coordinates** | vector3(-590.5323, 2067.587, 131.1351)
**Steam ID** | steam:110000104cdce8c
**Discord ID** | discord:239898223462842368
**Citizen ID** | AYD02331
**Character Name** | Frank Peters

**Comment by Dimmies** [comment]
This seems to be working as intended, you'll need to visit the explosive mines (towards the middle of the map) and find a point where you can place the exploisive, if you aren't already.
