### ISSUE TITLE
TTwitter Pic

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1527]
#### __Description__ 
I have not been able to take and send a picture though Twitter for a week or so. I just get a black square with a red x. Attched is a F8 error
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(405.4383, 6785.789, 3.148851)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
https://steamuserimages-a.akamaihd.net/ugc/1865066590346988571/E92891A01B61A5B115125D8BDA586F742BD04EF2/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false
