### ISSUE TITLE
No ATM at Casino 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#1529]
#### __Description__ 
No ATM at Casino 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(921.3118, 49.06926, 80.27908)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | DAH53801
**Character Name** | Sonny Ajello

**Comment by Dimmies** [comment]
It's been moved - After you enter the casino, it's in the room to the left.
