### ISSUE TITLE
Camera buttons in character creation

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#158]
#### __Description__ 
they result in some pretty wild angles - some not even pointing at the character
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(280.14, -656.0511, -16.97302)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | LWT55589
**Character Name** | Chad Frick

**Comment by Dimmies** [comment]
Camera control should be a bit better now. It should now always point to your character
