### ISSUE TITLE
Can't use Inked Duffle Bag

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#16]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(76.82188, 221.9563, 108.681)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
Seems to be working https://i.imgur.com/3OQVCo3.png
