### ISSUE TITLE
F1 and F2

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#160]
#### __Description__ 
So when i use F1 and F2 at the same time my F2 menu stays up and i can not do anthing so i have to fly out and in 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ashkka
**Coordinates** | vector3(-60.75824, -1340.594, 29.26273)
**Steam ID** | steam:11000010539944b
**Discord ID** | discord:335123983894708224
**Citizen ID** | DWW61043
**Character Name** | Ash Smith

**Comment by Dimmies** [comment]
You can now fix most UI by running `/uirestart` (or just `uirestart` in F8
