### ISSUE TITLE
[BUG] First Spawn Dead

### ISSUE THREAD

**Issue by YokedGorilla** [TheHiveRP/HiveIssues#162]
**Describe the bug**
After i initially selected my character slot to create a character i then was shown the apartment selection screen. After selecting the integrity way apartments it came up on my screen to respawn, then fell through the world for 4 or 5 seconds before being dropped incapacitated in my apartment with the character customization screen open.

**To Reproduce**
1. Go to 'select new character slot'
2. Click on 'The integrity way apartments'

**Expected behavior**
I expected to be dropped into my apartment still standing with the customization screen up.
![BUG 1 1](https://user-images.githubusercontent.com/88942267/129455271-826e4edd-ec4f-4b57-b84f-0ff205ce1889.jpg)
![BUG 1 2](https://user-images.githubusercontent.com/88942267/129455275-68784418-0255-4b4a-82e5-0c307669c064.jpg)

**Screenshots**
If applicable, add screenshots to help explain your problem as well as help find the cause/solution. This includes screenshots of your F8 console.

**Additional context**

**Comment by Dimmies** [comment]
I've added some extra health checks when initially spawning. This should solve this issue!
