### ISSUE TITLE
Switchblade Knife

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#165]
#### __Description__ 
The switchblade knife is pulled out from the players back like other weapons. Is it not meant to flick out - like a switchblade?
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(816.9766, -2127.57, 28.86921)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
These were never meant to be sold, removed from the weapon shop
