### ISSUE TITLE
Banking

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#169]
#### __Description__ 
Apparently you can overdraft your account to no limit, Brian tried it by paying off a car fully and is currently -17390 in his checking

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(230.9349, -801.684, 30.53391)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Going negative is fine, I've made it so you can't pay off your car if you don't have enough money
