### ISSUE TITLE
When police recieve a police call from the app, it doesn't show a notification

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#17]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(76.47216, 221.1999, 108.6835)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
This seems to be working? https://i.imgur.com/C89adMi.png
