### ISSUE TITLE
Unending supply of minerals

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#174]
#### __Description__ 
At character creation there is an unending amount of minerals on the florr. Once they are picked they repopulate forever.

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(281.4867, -655.571, -76.97387)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | VSU81638
**Character Name** | Frank Kirabti

**Comment by Dimmies** [comment]
Duplicate of #171
