### ISSUE TITLE
tattoo shop

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#18]
#### __Description__ 
When you go to get tattoos, you get a black shirt put on your character, blocking arm and torso tattoos
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(321.5899, 172.0609, 103.7122)
Steam ID | steam:11000011b56c5c4
Discord ID | discord:612497931169169408
Citizen ID | DXN74618

**Comment by Dimmies** [comment]
This only happens on the live server due to custom clothing
