### ISSUE TITLE
Car Damaged on retieval

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#182]
#### __Description__ 
Retrieved car from garage by square and tire immediately blew on spwam
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(229.7078, -798.1995, 30.13391)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | VSU81638
**Character Name** | Frank Kirabti

**Comment by Dimmies** [comment]
This seems to happen because when the vehicle is spawned, the engine health is also set to what it was stored at. This causes the vehicle failure script to trigger. I'll look into this soon
