### ISSUE TITLE
Face Modification Reset

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#185]
#### __Description__ 
Any changes made at a barbers using face sliders is reset when you rejoin the server. So you rejoin in the state your character was first made.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(287.0453, -103.7726, 69.96062)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
Disabled face sliders, it was an unfinished test.
