### ISSUE TITLE
pearl colors on cars

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#186]
#### __Description__ 
tired changing the pearl on my car and it didnt change. tried multiple times

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(1179.905, 2651.165, 37.42897)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by Dimmies** [comment]
Fixed
