### ISSUE TITLE
Missing radio update

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#188]
#### __Description__ 
Also missing toolbox and tools. All items were bought at the same time. I still have the lockpicks that were bought at the same time.
#### __Evidence__ 
na
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(232.2832, -753.4434, 30.8264)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | VSU81638
**Character Name** | Frank Kirabti

**Comment by Dimmies** [comment]
Merge with #187
