### ISSUE TITLE
Car Windows

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#189]
#### __Description__ 
Car windows are breaking without me crashing, I parked the car and the windows were broken when I walked back towards it from the bank, it's happened quite a bit.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Curtis
**Coordinates** | vector3(185.3728, -1015.926, 29.11203)
**Steam ID** | steam:1100001116d7bcc
**Discord ID** | discord:360933761849884674
**Citizen ID** | ETC02890
**Character Name** | Curtis Prophet

**Comment by Dimmies** [comment]
Added some controls, they can be found in Radial Menu under Vehicle Controls (while you're in a vehicle)
