### ISSUE TITLE
Fishing is super fast for some people

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#19]
#### __Description__ 
Was working fine for me but Brody, Cody and Pete all had super sensitive fishing
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(-1534.457, -1270.937, 1.754759)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
Fishing is being remade
