### ISSUE TITLE
armor persistence

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#192]
#### __Description__ 
after crash logout or restart armor does not persist
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Jollyrogerz
**Coordinates** | vector3(465.0519, -990.572, 30.69199)
**Steam ID** | steam:11000010163473c
**Discord ID** | discord:141870278446678016
**Citizen ID** | JRW73305
**Character Name** | Johnny Rogerz

**Comment by Dimmies** [comment]
Apparently Hunger and Thirst recover when you relog

**Comment by Dimmies** [comment]
Hunger/Thirst resets to 100 after relogging too
