### ISSUE TITLE
can see /me from others over me

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#193]
#### __Description__ 
no one is around me and i will randomly see someones /me command ove my head
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(2581.432, 2714.304, 42.21922)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by Dimmies** [comment]
Fixed
