### ISSUE TITLE
Pistol Gone

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#195]
#### __Description__ 
Bought pistol and puulled over to use. The pistol then disapperaed.

#### __Evidence__ 
na
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(811.4703, -2156.428, 29.61902)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
Similar to #187
