### ISSUE TITLE
Mining (Inventory Full)

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#199]
#### __Description__ 
While mining, it will allow you to continue to mine & believe you are collecting materials whilst your inventory is actually full and you are not collecting any materials.
#### __Evidence__ 
n/a
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(2959.168, 2789.338, 40.27195)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
I've added a notification that shows when something tries to add to your inventory but fails because of weight
