### ISSUE TITLE
Clothing store camera 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#200]
#### __Description__ 
camera in clothing store does not rotate around the character insteast it spins the room around 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VaporsTV
**Coordinates** | vector3(421.8069, -808.1396, 29.49114)
**Steam ID** | steam:11000010a881792
**Discord ID** | discord:105855026240462848
**Citizen ID** | ITG73905
**Character Name** | Oliver Clothesof

**Comment by Dimmies** [comment]
Use A and D to rotate your character, the arrows rotate the camera.
Also added control display for A and D on the clothing menu
