### ISSUE TITLE
Can beep radio while dead

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#202]
#### __Description__ 
Not sure if you can talk while dead, but can beep
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(525.1282, -936.1378, 18.63075)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | FMJ41908
**Character Name** | Benjamin Adams

**Comment by Dimmies** [comment]
Fixed
