### ISSUE TITLE
Reveive bug is doing Simeon job

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#203]
#### __Description__ 
If taken to front desk cannot  use revive. Says uanble performing another task. Beleive this is due to the curretn Simeon task I was on using "E"

#### __Evidence__ 
na
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(363.8206, -589.09, 44.21378)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
This is intended, you can go to the beds in the back and manually lay in them to revive/heal. I'll add checking in while dead to the todo list
