### ISSUE TITLE
downed people cant check in to the hospital

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#205]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(307.4768, -590.4487, 43.28406)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
This is intended, you can go to the beds in the back and manually lay in them to revive/heal. I'll add checking in while dead to the todo list
