### ISSUE TITLE
Revive update with pic

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#206]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2577124815
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(308.2762, -592.3828, 43.27965)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
This is intended, you can go to the beds in the back and manually lay in them to revive/heal. I'll add checking in while dead to the todo list
