### ISSUE TITLE
Calling is a little broken

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#207]
#### __Description__ 
If you call someone and they don't answer, they're set as still on a call.
If you recieve a call from someone and dont answer in time, you can still see the incoming call screen (or the little notification thing)

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(481.0025, -1012.739, 26.27321)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | FMJ41908
**Character Name** | Benjamin Adams

**Comment by Dimmies** [comment]
Texting Error: https://i.imgur.com/Pb3Hk1G.png
