### ISSUE TITLE
/me is showing global. Apparently someone likes to eat ass

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#208]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(193.9338, -933.4279, 30.68681)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Already fixed in next update
