### ISSUE TITLE
Notifications UI has scrollbar

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#21]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(1356.941, -546.3172, 46.19061)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
Not a big issue at all

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
