### ISSUE TITLE
E while in Apt

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#217]
#### __Description__ 
While trying to harvest plants in the apt, I end up in the elevator even when I'm not that close to the door. Maybe make zone around door smaller.
#### __Evidence__ 
na
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(284.5959, -655.7376, -106.9739)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
Lowered from 3.0 to 2.0
