### ISSUE TITLE
Apt Stash

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#218]
#### __Description__ 
When attempting to access stash it says I have none. There is no visdula of one either, jst the E to access. 
No errors.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(284.6534, -655.1156, -106.9739)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
Merge #220
