### ISSUE TITLE
House Stashes aren't working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#22]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(1352.428, -556.187, 46.19066)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
Apartments too
