### ISSUE TITLE
cant get into my appartment nothing shows up in the elevator

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#223]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(276.7709, -644.3669, 42.01864)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Fixed in next update
