### ISSUE TITLE
Apt

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#225]
#### __Description__ 
Don't have prompt to enter apt.
#### __Evidence__ 
na
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(289.4316, -650.9494, 42.01955)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
Fixed in next update
