### ISSUE TITLE
 (testing meth) quality was 121 and no items to use meth in server

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#231]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(1991.023, 4960.226, 31.35526)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Fixed having > 100 quality
