### ISSUE TITLE
Mechanic Boss Menu

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#237]
#### __Description__ 
Boss Menu wont allow me to use it... can see it and click on it but doesn't pop up anything
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(-67.55558, -1327.78, 29.26825)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | THQ84246
**Character Name** | Treyvon Williams

**Comment by Dimmies** [comment]
Can't Replicate

**Comment by Dimmies** [comment]
Wasn't Rank 4
