### ISSUE TITLE
Rockford Records Blip

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#242]
#### __Description__ 
Possible marker location for Rockford Records
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(374.6239, -211.2798, 56.81515)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | THQ84246
**Character Name** | Treyvon Williams

**Comment by Dimmies** [comment]
Added to Todo list
