### ISSUE TITLE
car paint is not saving

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#244]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(291.0439, -556.2341, 43.18792)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Merge to #244
