### ISSUE TITLE
able to plant more than 10 weed plants

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#245]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(283.887, -655.4985, 13.02609)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
You can plant 20, not 10
