### ISSUE TITLE
Vehicle Liveries and health isn't saving?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#256]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(44.48651, -1502.1, 29.13896)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | IVO92547
**Character Name** | Miles Long

**Comment by Dimmies** [comment]
Merge to #236
