### ISSUE TITLE
Dropped Items Arrow not deleting sometimes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#262]
#### __Description__ 
When someone drops an item on the ground and picks it up the arrow indicator doesnt disappear 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chenneth
**Coordinates** | vector3(762.9824, 2.102555, 62.92628)
**Steam ID** | steam:11000010a313c85
**Discord ID** | discord:107694309620334592
**Citizen ID** | XYB92458
**Character Name** | Kenny Hendrix

**Comment by Dimmies** [comment]
Added another check to make sure these get cleaned up
