### ISSUE TITLE
vehicle paint

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#267]
#### __Description__ 
just bought a bike from pdm and painted it blue at pdm. cant repaint it at bennys

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(-211.55, -1324.55, 30.40622)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by Dimmies** [comment]
Removed for now
