### ISSUE TITLE
steal shoes doesnt work

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#270]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(155.8797, -998.5115, 29.35397)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Disabled for now
