### ISSUE TITLE
add island bar/nightclub?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#271]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-1480.193, -1474.32, 16.045)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Added to todo list
