### ISSUE TITLE
Dumpster Searching Suggestion 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#278]
#### __Description__ 
Adding more items to be found inside the dumpster... like tv or a picture that you will hold like the box animation from the go postal job that you have to store in the back of your car 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(-195.2411, -1531.976, 33.79012)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | THQ84246
**Character Name** | Treyvon Williams

**Comment by Dimmies** [comment]
Added to todo list
