### ISSUE TITLE
'Not Enough Baggies' Error when harvesting weed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#279]
#### __Description__ 
When harvesting the weed plants I had a stack of 50 baggies. I harvested 48 baggies which meant I had a stack of 2 baggies left. I then received the "not enough baggies" warning. I bought an additional 300 baggies and still received "not enough baggies". The reason was I had a stack of 300 baggies and a stack of 2 baggies. Not major but soemthing to look at and/or mention to players.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(284.6532, -655.1199, 13.0261)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
This happens because it gets the first stack of empty weed bags in your inventory, if the first stack is less than what it needed, it'll cause this error. You can fix this by either stacking all of your baggies into 1 stack or by moving the larger stack in front of the smaller stack
