### ISSUE TITLE
cant see weed plants until you harvest one then they all appear

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#292]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(259.6902, -639.3914, 40.49117)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
The plants are there, they are just on top of the apartment shell.
