### ISSUE TITLE
3-Card Poker Error

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#3]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
https://i.imgur.com/zXM9Veh.png
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(949.0049, 42.18207, 75.31728)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
Happens when you enter the casino
