### ISSUE TITLE
Drug Sales

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#302]
#### __Description__ 
When you successfully sell drugs to an NPC, they can get stuck in the handshake animation
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-1199.538, -1538.822, -14.64099)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Sold 100 weed just now, unable to replicate.
