### ISSUE TITLE
Local vehicle despawn too quickly

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#308]
#### __Description__ 
Local had a car accident and died. Towed car to PD and went into front to look for police. came back out and local car with dead body had despawned from back of truck.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(407.041, -1003.364, 29.3535)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
This is unfortunately something I don't think can change. You can lockpick the vehicle and the server will remember it.
