### ISSUE TITLE
Can't craft pistol parts into a pistol

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#31]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(1345.493, -547.5556, 46.19065)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.11.0`
