### ISSUE TITLE
raise the repair cost from bennys if there is a mechanic online

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#310]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-417.929, -937.7151, 37.03657)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Added to todo list
