### ISSUE TITLE
mechanics cant use /extras. The menu comes up but he wasnt able to select anything

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#311]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-39.11366, -1375.118, 29.39164)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Can't replicate, the vehicle needs to have extas/liveries for the buttons to show
