### ISSUE TITLE
Towtruck

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#312]
#### __Description__ 
Could not tow vehicle and message said towtruck was already towing a vehicle.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(177.824, -1013.425, 29.30954)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
More Info: #314

**Comment by Dimmies** [comment]
New Towing mechanics coming next update
