### ISSUE TITLE
3 Card poker isn't working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#316]
#### __Description__ 
Unable to see my cards when playing 3 card poker. Also a constant pinging noise which is annoying all hell.
#### __Evidence__ 
https://i.imgur.com/tybp8QE.jpg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(1025.693, 56.75308, 72.4761)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
See #344
