### ISSUE TITLE
Police Boat 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#320]
#### __Description__ 
No where to spawn these for water chases 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(121.3051, -1454.115, 28.89336)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | DAH53801
**Character Name** | Sonny Ajello

**Comment by Dimmies** [comment]
Added to todo list
