### ISSUE TITLE
Towing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#321]
#### __Description__ 
Attempted to tow Jamal's car and upon using tow it disappeared. No error
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-73.19544, -1317.966, 29.16239)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
New Towing mechanics coming next update
