### ISSUE TITLE
add island bar

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#322]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-1672.458, -1291.501, 46.45406)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Duplicate of #271
