### ISSUE TITLE
phone shows military time next to regular time at the top left. Not that big of a deal 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#325]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-48.75942, -1096.229, 26.42701)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | FCO12745
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
This is intentional, one is real time, one is in-game time
