### ISSUE TITLE
car Boost

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#328]
#### __Description__ 
Drove entire area of shitty car boost and threre were no vehicles in the area.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-929.7756, -876.0839, 14.90536)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
#### __Description__ 
After boosting car, beeing battered by a local with a bat and coming back to simeons he is saying its not the car he was looking for. think he's wrong
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VisionzAx
**Coordinates** | vector3(-1154.35, -2002.588, 12.42508)
**Steam ID** | steam:110000136d79dfe
**Discord ID** | discord:527475418299629568
**Citizen ID** | BRI89099
**Character Name** | Kilo Broker

**Comment by Dimmies** [comment]
I was able to replicate this at some point, but I'm unsure of what causes this. If you have more information, please let me know
