### ISSUE TITLE
Store Helicopter? But not in a helicopter

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#330]
#### __Description__ 
I spawned in a gauntlet hellfire at pd, and the '[E] Store helicopter' prompt is up on my screen. Left PD, Still there
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(425.5706, -1022.47, 28.39645)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by PyotrPalach** [comment]
The store helicopter prompt occurs when you get a vehicle from MRPD garage as police and at the Pillbox Hospital garage as an emt. Doesn't matter what vehicle you get, the prompt shows up and stays until you log out.
