### ISSUE TITLE
a couple scratchers randomly disapeared as soon as I started scratching them

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#332]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-1226.111, -900.2726, 12.33125)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
This happens if you spam use the scratch off item
