### ISSUE TITLE
cant let people into your apartment

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#339]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(276.8467, -640.9161, 42.01865)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Only on stanier
