### ISSUE TITLE
sirens from police cars are randomly going off

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#341]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(448.8281, -977.6224, 25.30596)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
Only on stanier
