### ISSUE TITLE
Casino 3-Card Poker Hand is not visible [BUG] 

### ISSUE THREAD

**Issue by Dopykoh** [TheHiveRP/HiveIssues#344]
**Describe the bug**
You are unable to see your hand in 3 card poker when it's dealt and there is a nonstop ding while seated at the table.

**To Reproduce**
1. Go to Casino 
2. Play 3-Card Poker
3. Once your hand is dealt you can't see the cards handed to you.

**Expected behavior**
Being able to see the cards in my hand.

**Screenshots**
https://imgur.com/gallery/fL15Zdz

**Additional context**
There is also a dinging that does not stop while sitting and playing at the table.
The file is too big to attach so I made a streamable.
https://streamable.com/6jxpah

**Comment by Dimmies** [comment]
I've disabled 3-Card poker as of now and replaced it with another Blackjack table. We'll revisit 3-Card poker again at a later date.
