### ISSUE TITLE
Large Soda not filling thirst

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#356]
#### __Description__ 
I bought a large soda at up and atom and after drinking it my thirst didn't change. Didn't get any screenshots. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(86.69576, 282.5312, 110.2306)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | VJY76502
**Character Name** | Phoebe Allen

**Comment by Dimmies** [comment]
Merging with #346
