### ISSUE TITLE
Boss menu for Chief of ems

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#358]
#### __Description__ 
Not working 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(334.8234, -594.0587, 43.28409)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | UBD72148
**Character Name** | Rudy Domino

**Comment by Dimmies** [comment]
Duplicate of #352
