### ISSUE TITLE
Personal Vehicle Despawn

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#360]
#### __Description__ 
Personal Vehicles despawned after leaving the area, however I did not go too far from where it was left. Vehcile was left in lower lot of MRPD, and the farthest I went was over to the Tuner Shop and to PDM/Bennys
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(294.9869, -346.4225, 44.50357)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
#### __Description__ 
went into the arcade run around in there looking at the arcade machines come back out side and my bike was misssing it was defo locked i also had this issue down at the lorry place with my car i returned the lorry and my car was gone as well 
#### __Evidence__ 
no clip or screenshot sorry
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TheBadGuy
**Coordinates** | vector3(-1266.01, -269.4343, 38.92936)
**Steam ID** | steam:11000010b339ff6
**Discord ID** | discord:431958633656483840
**Citizen ID** | EIB50113
**Character Name** | Prince Devitt

**Comment by Dimmies** [comment]
#### __Description__ 
Went out on a call for a tow, when I got back to the mechanic shop my bike was gone. Wasn't in the garage, wasn't impounded. Presumed stolen but heard people have had issues with vehicles vanishing. Whilst doing the mechanic job I've experienced not being able to unlock my own vehicle after having to jimmy a car open or being in a car I'm recovering. Feels like I'm missing part of the ownership of my own vehicle - just thought it might have something to do with that.
#### __Evidence__ 
https://imgur.com/RZ8MI9s
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-84.31992, -1323.745, 29.28408)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
#### __Description__ 
Went out on a call for a tow, when I got back to the mechanic shop my bike was gone. Wasn't in the garage, wasn't impounded. Presumed stolen but heard people have had issues with vehicles vanishing. Whilst doing the mechanic job I've experienced not being able to unlock my own vehicle after having to jimmy a car open or being in a car I'm recovering. Feels like I'm missing part of the ownership of my own vehicle - just thought it might have something to do with that.
#### __Evidence__ 
https://imgur.com/RZ8MI9s
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-84.31992, -1323.745, 29.28408)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
I've recently had this happen to me, but am unable to replicate it. Needs more info

**Comment by Dimmies** [comment]
#### __Description__ 
Car wont show up on phone app says waypoint set but no waypoint is showing up.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TheVanillaGorilla89
**Coordinates** | vector3(814.5757, -1470.387, 26.83188)
**Steam ID** | steam:11000013fbef10b
**Discord ID** | discord:682007977950969876
**Citizen ID** | XDL67461
**Character Name** | Drew Down

**Comment by Dimmies** [comment]
#### __Description__ 
I had to relog to fix my phone and when I logged back in my bike poofed 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | SniperEvolving
**Coordinates** | vector3(-48.80924, -1116.761, 26.43537)
**Steam ID** | steam:110000108f231ca
**Discord ID** | discord:118549893038997506
**Citizen ID** | MOF09179
**Character Name** | Evo Thompson

**Comment by Dimmies** [comment]
#### __Description__ 
I parked my car near the postal place, and i picked up the job overthere. when i finished the postal route i came back to the postal and my car was no longer there. looked at my phone and tried to gps mark it but its not marking the vehicle. i went to the garage and its telling me its outside. i went to the impound lot and i have no vehicles in there.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TTV/Skywolfieee
**Coordinates** | vector3(-212.627, -1161.719, 23.16379)
**Steam ID** | steam:1100001034ad670
**Discord ID** | discord:114666562438299651
**Citizen ID** | UKX40861
**Character Name** | Memphis Raines

**Comment by Dimmies** [comment]
#### __Description__ 
My motorcycle despawned and when I added the waypoint on my phone app, it says that it marked the location but nothing comes up on the map so I have no clue how to find it
#### __Evidence__ 
https://i.imgur.com/hve5Mcw.jpeg https://i.imgur.com/rwXiI2C.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Mr_B_G
**Coordinates** | vector3(1518.462, -2048.631, 76.89854)
**Steam ID** | steam:11000013eadaf56
**Discord ID** | discord:488390960426778644
**Citizen ID** | JUT08982
**Character Name** | Sean Taylor
