### ISSUE TITLE
Character rest at Barber Shop

### ISSUE THREAD

**Issue by eamundson1** [TheHiveRP/HiveIssues#366]
**Describe the bug**
FYI
Went to the barber shop and went through selections. Ended up not changing anything and exiting. Upon exiting I was a default ped with default clothes. I went to the clothing shop but nothing changed. 
I then went to my apartment and chose my saved outfit. The clothes changed to the correct outfit but character remained default. I didn't want the character saved so I exited game by using ctrl alt delete. Came back in game and everything was rest to normal.
Didn't see any errors.

**Comment by Dimmies** [comment]
Duplicate of #363
