### ISSUE TITLE
Treat Injuries not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#367]
#### __Description__ 
When we go to treat minor injuries, Treat wounds is not working correctly it's healing you to about half health and then stops, from there no health increase is shown. But when we use revive it heals you to full. 
#### __Evidence__ 
Sorrry no screen shots of the bug but I will try to get one.
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Sayahchan
**Coordinates** | vector3(304.3387, -585.9322, 43.28407)
**Steam ID** | steam:11000010413aae1
**Discord ID** | discord:397959613061791745
**Citizen ID** | FFU45850
**Character Name** | Charlene Garcia

**Comment by Dimmies** [comment]
Treating injuries only heal damaged ped bones. I've added a heal button to the EMS Toolbox to make it easier to heal players!
