### ISSUE TITLE
Core Error

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#37]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
https://i.imgur.com/hk1R3EZ.png
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(1992.919, 4962.375, 31.35526)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
This happens if you try to set someones job rank to one that doesn't exist.

Ex: /setjob 1 unemployed 10 (rank 10 doesn't exists)
