### ISSUE TITLE
Towtruck Bugs

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#370]
#### __Description__ 
I attempted to tow the winky jeep, which I had just bought, and the towtruck and jeep went up, into the air, and disappeared. No error code.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-55.39566, -1041.612, 28.21048)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
#### __Description__ 
Attempted to tow Uncle J's Suv and when cable attached it went out of sight and all over the place. Jumped in towtruck to see where it would go and it fell through the earther. Ended back up in same location with vehicle, properly, on tow bed. However towtruck was damaged.
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2594851865    https://steamcommunity.com/sharedfiles/filedetails/?id=2594851810
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-595.4882, 253.7909, 82.30621)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
#### __Description__ 
The police car will get pulled up by the cable but once in position where the cable lets and the car should lock in place, it just slides back off. No error code.
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2594875925
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-91.97588, -1372.841, 29.35576)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
#### __Description__ 
Responded to a tow job, as I selected the tow option from the side of the tow truck, both the tow truck and the car I was trying to disappeared into the air. Bryan came to pick me up and think he saw it in the air doing mach1
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-429.3902, -1122.01, 29.02961)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins
