### ISSUE TITLE
Tow Bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#373]
#### __Description__ 
Attempted to tow Uncle J's Suv and when cable attached it went out of sight and all over the place. Jumped in towtruck to see where it would go and it fell through the earther. Ended back up in same location with vehicle, properly, on tow bed. However towtruck was damaged.
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2594851865    https://steamcommunity.com/sharedfiles/filedetails/?id=2594851810
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-595.4882, 253.7909, 82.30621)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Merged with #370
