### ISSUE TITLE
Tow Police car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#374]
#### __Description__ 
The police car will get pulled up by the cable but once in position where the cable lets and the car should lock in place, it just slides back off. No error code.
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2594875925
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-91.97588, -1372.841, 29.35576)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Merged to #370
