### ISSUE TITLE
Apartments

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#375]
#### __Description__ 
I spawned in Dende's apartment when I tried to enter mines, he was already in his.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Curtis
**Coordinates** | vector3(284.5788, -655.0723, -16.97389)
**Steam ID** | steam:1100001116d7bcc
**Discord ID** | discord:360933761849884674
**Citizen ID** | ZWP32858
**Character Name** | Curtis Prophet

**Comment by Dimmies** [comment]
#### __Description__ 
everyone is in the same apartment when they enter. means you see everyone
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VisionzAx
**Coordinates** | vector3(285.0216, -651.0728, -16.97389)
**Steam ID** | steam:110000136d79dfe
**Discord ID** | discord:527475418299629568
**Citizen ID** | BRI89099
**Character Name** | Kilo Broker
