### ISSUE TITLE
Phone time

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#376]
#### __Description__ 
Phone has the time on the middle of the screen and then twice on the top left of the homescreen.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Curtis
**Coordinates** | vector3(76.78931, -1646.395, 28.79786)
**Steam ID** | steam:1100001116d7bcc
**Discord ID** | discord:360933761849884674
**Citizen ID** | ZWP32858
**Character Name** | Curtis Prophet

**Comment by Dimmies** [comment]
This is intended
