### ISSUE TITLE
cannot put helicopters away as a cop on the roof of MRPD

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#381]
#### __Description__ 
i cant seem to find a way to store the helicopters after bringing them out of the garage at mrpd on the roof
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Greg
**Coordinates** | vector3(451.8844, -980.603, 43.69156)
**Steam ID** | steam:11000010a68b266
**Discord ID** | discord:208794468495785984
**Citizen ID** | QYW53527
**Character Name** | Greg OConor

**Comment by Dimmies** [comment]
I believe this was due to using the wrong helipad. There are 2 on the roof and after testing it seemed to work fine.
