### ISSUE TITLE
Stolen Weapon Ammo

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#385]
#### __Description__ 
Had my pistol stolen but when I bought a new one I still ahd my old ammo loaded in my new gun
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(251.8785, -48.32812, 69.94106)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
This is currently intended behavior.
