### ISSUE TITLE
Lesters House Job

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#386]
#### __Description__ 
I could be wrong, but after trying to hit up a house robbery, it said there wasn't enough cops on right now. Even though I swear there's atleast 4 cops around rn, granted could be my bad but just incase
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Am Mintal Min
**Coordinates** | vector3(1171.44, -249.1593, 68.48374)
**Steam ID** | steam:11000011c77ebd6
**Discord ID** | discord:375302688663142420
**Citizen ID** | ZPB54826
**Character Name** | Ice Carter

**Comment by Dimmies** [comment]
At this point in time, there were only 2 cops online. House robberies require 3.
