### ISSUE TITLE
Radio not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#387]
#### __Description__ 
i am on radio 42, i am talking but fiend cant hear me, i can hear him perfectly and he can hear my radio clicks, was working fine then just stopped
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VisionzAx
**Coordinates** | vector3(-342.3576, -1148.349, 26.39211)
**Steam ID** | steam:110000136d79dfe
**Discord ID** | discord:527475418299629568
**Citizen ID** | BRI89099
**Character Name** | Kilo Broker

**Comment by Dimmies** [comment]
This is usually caused by out VOIP solution in the server, to fix this:

1. Go to GTA Settings
2. Go to Voice Chat tab
3. Set Voice Chat Enabled to OFF
4. Wait a second
5. Set Voice Chat Enabled to ON

If this doesn't resolve the issue, double check your input/output devices are correct.
