### ISSUE TITLE
Can't you Inventory

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#389]
#### __Description__ 
have flown in. and can't access inventory and use phone at all
#### __Evidence__ 
https://youtu.be/1Y2tpTxG-sc
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VisionzAx
**Coordinates** | vector3(-39.98555, -757.2768, 32.70152)
**Steam ID** | steam:110000136d79dfe
**Discord ID** | discord:527475418299629568
**Citizen ID** | BRI89099
**Character Name** | Kilo Broker

**Comment by Dimmies** [comment]
This was caused by something something (being cuffed or dead) not being reset.
