### ISSUE TITLE
Chino Custom

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#390]
#### __Description__ 
When pulling the vehicle "Chino Custom" out of the garage, sometimes it will come out in a hard-top variant, sometimes in a no-top variant. There is no way to purchase hardtop/notop at Benny's.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(277.6946, -647.2632, 42.01863)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
This is caused by an extra being turned on.

At the moment there isn't an easy/best solution for this so it'll remain open until we can find a good solution for this.

**Comment by Dimmies** [comment]
Extras now save with vehicles. You can head to the mechanic shop and have them put on the extra.
