### ISSUE TITLE
Turbo/Neon lights upgrades not working on Chino Custom

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#393]
#### __Description__ 
Specifically on the Chino Custom, seems like the vehicle is actually slower with turbo equipped than before. Additionally neon lights are not working for this vehicle
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(-34.74268, -1053.247, 27.75815)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
This vehicle is a default GTA vehicle, if neon lights don't work on it, it's intended.
As for the turbo, I tested it out and while it doesn't go significantly faster, it does go a bit faster and has better acceleration. As said before, this vehicle is a default GTA car so it's not something we did. If you don't hear a turbo, it wasn't correctly installed on the vehicle. I checked what I believe to be your Chino and it says it's supposed to have turbo so I assume it's just a little less than what you expected. Next time you're in-game see if you hear a turbo, if you don't let me know.
