### ISSUE TITLE
Put in Vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#399]
#### __Description__ 
When I click f1 and put player in vehicle and someone is standing next to me it just puts them in, they dont need to be cuffed or anything? I figured they would need to be downed or cuffed or ziptied
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NewwMann
**Coordinates** | vector3(2413.939, 2931.389, 40.14015)
**Steam ID** | steam:11000010ddf9d03
**Discord ID** | discord:105289786343878656
**Citizen ID** | ZTL72035
**Character Name** | Jesse Mac

**Comment by Dimmies** [comment]
This is intended
