### ISSUE TITLE
Vehicle Liveries

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#405]
#### __Description__ 
Sometimes vehicle liveries randomly disappear. No further details to replicate or actions that caused the bug at this time
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(154.3908, -420.0172, 40.4747)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
#407

**Comment by Dimmies** [comment]
I can't seem to get this to replicate enough to figure out what's causing this. If anyone has any more info on this, feel free to add it
