### ISSUE TITLE
Vehicle Liveries (update)

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#407]
#### __Description__ 
Seems like the livery disappeared while my car was out of the garage and I left and reconnected to the server.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(-805.2327, -1656.672, 15.91547)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
Merged with #405
