### ISSUE TITLE
bandages

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#409]
#### __Description__ 
i used 2 bandages and my minor bleeding didnt stop at all. i then bed out because of this
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VisionzAx
**Coordinates** | vector3(2680.286, 3282.424, 55.24115)
**Steam ID** | steam:110000136d79dfe
**Discord ID** | discord:527475418299629568
**Citizen ID** | BRI89099
**Character Name** | Kilo Broker

**Comment by Dimmies** [comment]
Bandages do heal bleeds, but it may take a few before it heals all bleeds. If this happens again, try using a few more.
