### ISSUE TITLE
Some cars don't give you the keys when you get them from the garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#41]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(209.068, -808.882, 30.51778)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
I'm not having this issue anymore and it hasn't been reported other than this one incident.
