### ISSUE TITLE
Tow Truck Launched

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#416]
#### __Description__ 
Responded to a tow job, as I selected the tow option from the side of the tow truck, both the tow truck and the car I was trying to disappeared into the air. Bryan came to pick me up and think he saw it in the air doing mach1
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-429.3902, -1122.01, 29.02961)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
Merged to #370
