### ISSUE TITLE
Impounding Vehicles

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#420]
#### __Description__ 
PD and civilian cars cant be impounded. Tried Inside, tried outside, cant return them to the PD garage, cant DV them
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-57.61024, -1114.099, 26.43632)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
I believe this is related to #419

If anyone has any more information on this, feel free to add.

**Comment by Dimmies** [comment]
Related to #419
