### ISSUE TITLE
Hunting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#422]
#### __Description__ 
I have been testing out Hunting for my first activity and hope this is actually a bug so I dont waste your time. Placing down bait works fine, but it seems no matter how far away from the bait placemenet I am the first animal will always say "The animal was scared off" or something similar, the second one says "You hear something approaching" but I have yet to actually spot an animal. Tried staying crouched down, but nothing is approaching the bair or the area around me. Reporting it in case its broken.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Louie
**Coordinates** | vector3(1899.41, 6507.549, 92.56214)
**Steam ID** | steam:11000010376d6f7
**Discord ID** | discord:254188195263152129
**Citizen ID** | JTU79937
**Character Name** | Alfredo Rossi

**Comment by Dimmies** [comment]
#### __Description__ 
Once Bait is placed, you wait the time and no matter what you do the animal gets scared off, a second prompt comes up shorlty after saying something is approaching but nothing shows up/
#### __Evidence__ 
https://cdn.discordapp.com/attachments/876141775448854568/886555441272852490/unknown.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | iTzHoBBs
**Coordinates** | vector3(-769.4044, 5283.485, 87.59788)
**Steam ID** | steam:110000103ebb8a4
**Discord ID** | discord:386139575782998017
**Citizen ID** | WQM70520
**Character Name** | Martin Riggs
