### ISSUE TITLE
Gas Cans

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#423]
#### __Description__ 
When you use gas cans, they drop to the ground and don't work.

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Curtis
**Coordinates** | vector3(381.4706, 314.2633, 103.1767)
**Steam ID** | steam:1100001116d7bcc
**Discord ID** | discord:360933761849884674
**Citizen ID** | ZWP32858
**Character Name** | Curtis Prophet

**Comment by Dimmies** [comment]
#### __Description__ 
I filled Bryans car up with fuel from teh gas can and it worked in my eyes but when he got in it was back to the original 17%. Then when I got in (after he had already been in it before me) I also saw the 17% - I should have got in the vehicle before and after filling it up but I only realised this with hindsight.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-84.63699, -1329.646, 29.29218)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins
