### ISSUE TITLE
Rank

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#43]
#### __Description__ 
Rank is not getting reset when switching jobs 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(312.9318, -277.6963, 54.17429)
Steam ID | steam:11000010c834ebf
Discord ID | discord:424994252775358465
Citizen ID | OAH04677

**Comment by Dimmies** [comment]
Unsure of what causes this, but theres very few cases of this happening in the live server.
