### ISSUE TITLE
meth

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#430]
#### __Description__ 
Can someone that knows how to get 100% test meth please, we are doing the same thing after geting a high number and are then getting another result
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | VisionzAx
**Coordinates** | vector3(1987.353, 4959.384, 31.35524)
**Steam ID** | steam:110000136d79dfe
**Discord ID** | discord:527475418299629568
**Citizen ID** | BRI89099
**Character Name** | Kilo Broker

**Comment by Dimmies** [comment]
Tested and it's working as intended. You must be missing a step or something
