### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by HanssonS** [TheHiveRP/HiveIssues#431]
Hello!

I have an idea of a business i wanna have here in Hive!.
It's a Tow & Repair business located in Sandy Shores in a building called Flywheels, located next to Sandy airfield.

 https://forum.cfx.re/t/release-flywheels-garage/1436833 

The Business is called " R.Williams Tow&Repair " Where we wanna have this tow truck

 https://www.gta5-mods.com/vehicles/ford-cargo-815-porto-seguro-els-dials

With possibly a remake of the texture on the truck with the company logo on it if possible.
We are mostly into repairing bikes and tow bikes from bikers around the city. but we love to help people with cars as well.
In the future we looking into expanding into the customization industry as well.

Ryan Williams is the founder of the company and he wanna get it started there. He is a former MC president of a club called LDMC that he have left and wants a change in his life. Ryan is born 1988, and been around that life for to long. But he still love bikes with all of his heart. That's why he wanna be more into helping bikers. But he wanna stay out of trouble.

If this sounds interesting and you guys have questions, hit me up on discord Hansson#8418

**Comment by Dimmies** [comment]
At this time, businesses will come at a later date. Our plan right now is to focus on getting the server stable before you go through the process of working on player owned businesses. You can still start and build your business through RP and work with what the server currently has to offer. The reason we are doing it this way to to make we don't put work into a business that is abandoned shortly after being implemented.

If you have an questions regarding businesses, feel free to ask in the Discord.
