### ISSUE TITLE
Underwater death

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#432]
#### __Description__ 
As soon as oxygen runs out its instant death, not sure if its a bug or meant to be like this

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | iTzHoBBs
**Coordinates** | vector3(-1863.314, -1195.239, -13.79771)
**Steam ID** | steam:110000103ebb8a4
**Discord ID** | discord:386139575782998017
**Citizen ID** | WQM70520
**Character Name** | Martin Riggs

**Comment by Dimmies** [comment]
You don't die instantly, just super fast. https://streamable.com/g3fy1n

I've increased the time you can be underwater by quite a bit so this should be easier to avoid.
