### ISSUE TITLE
Dropping items on the ground

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#434]
#### __Description__ 
Dropping items on the ground is still kinda buggy. I droped some basil on the ground earlier and noone was able to pick it up including myself. It just showed empty when I hit f2
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(217.5349, -798.7249, 30.27418)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | HAP03627
**Character Name** | Jamal Hendricks

**Comment by Dimmies** [comment]
The next update `alpha-1.40.0` should include possible fixes for this. If this happens again, please let me know
