### ISSUE TITLE
Selfie

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#436]
#### __Description__ 
Can't get selfie picture off screen. No error code.
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2600700324
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1174.907, -877.5121, 13.54203)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
`F8 > uirestart` should now fix this
