### ISSUE TITLE
Endless emotes when Bound to Num8

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#437]
#### __Description__ 
I bound "wait" to num8 and nothing happened so I tried "finger2" and nothing. So i pressed it roughly 10 times and nothing happened. Then all of a sudden the finger2 and wait emotes started happening on their own. Even after I raised my hands etc. Continued for 10+ mins until I did the "crossarms4" emote which was bound to num7 which works fine. No emotes in these besides the Hands up or crossarms4 are intentional and are happening on their own.
#### __Evidence__ 
https://streamable.com/tfjec4
https://streamable.com/uwwa30
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Bandiiit
**Coordinates** | vector3(455.8322, -994.4098, 30.69199)
**Steam ID** | steam:110000119a8c31a
**Discord ID** | discord:330777829161566210
**Citizen ID** | LDW19949
**Character Name** | Dante Stryker

**Comment by Dimmies** [comment]
#### __Description__ 
character is using "wait" emote without pressing any keybinds. i placed a bug report a couple days ago about what i think sparked this issue
#### __Evidence__ 
https://streamable.com/c49v7o
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Bandiiit
**Coordinates** | vector3(458.4064, -993.1426, 34.97172)
**Steam ID** | steam:110000119a8c31a
**Discord ID** | discord:330777829161566210
**Citizen ID** | LDW19949
**Character Name** | Dante Stryker

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
