### ISSUE TITLE
Explosive Mining Job has a bug?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#441]
#### __Description__ 
When I would start my mining job, after hitting the first vein I would get a constant pop-up that says: "Vein is Empty" and it doesn't ever go away, nor does it let me see other spots to mine. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Anjie
**Coordinates** | vector3(-595.6039, 2092.794, 131.4619)
**Steam ID** | steam:1100001074928e6
**Discord ID** | discord:262828827049197568
**Citizen ID** | JME34523
**Character Name** | Anjulie Hawthorne

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
