### ISSUE TITLE
Not allowing to send SMS on phone 

### ISSUE THREAD

**Issue by T2Slay** [TheHiveRP/HiveIssues#446]
It isn't allowing me to send SMS on the phone in the city if I have the number or not.

link to clip of bug:

https://youtu.be/tYUWh9YDJvE

**Comment by Dimmies** [comment]
@T2Slay Did you by chance edit the contact in that video?

I believe the issue is, when you edit it contact, it doesn't update until you relog which causes this same issues.

**Comment by T2Slay** [comment]
I discovered what the issue was. Because he didn't suggest his number and I took it from twitter it wouldn't let me contact him. But soon as he suggested it it would save him as a new contact and let me text/call him.

Apologies for wasting time in other cities we'd input the number etc. Maybe have option for both?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
