### ISSUE TITLE
MDT Person Search Improvement

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#45]
#### __Description__ 
When you search a name, you have to search a full first name or full last name. You can't search partial first names or partial last names
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(316.7633, -272.2054, 53.9156)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
Not really a "bug" more so an inconvenience. I'll take a look at this later

**Comment by Dimmies** [comment]
MDT is getting completely remade
