### ISSUE TITLE
Unable To Impound Broken Car At Impound Yard

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#453]
#### __Description__ 
After collecting a broken down/abandoned car with teh flatbed and taking it to the impound yard, I was unable to get the prompt to impound the vehicle whilst it was in the correct area. I can only presume this was because it was broken down and the engine wouldn't start. I was able to impound a local car and also got the prompt to impound my truck.
#### __Evidence__ 
https://imgur.com/fyw7OAt
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-238.0416, -1181.076, 22.69028)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
Related to #419
