### ISSUE TITLE
Bank Transfers / Eddie Russo / Administries#0001

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#454]
#### __Description__ 
With the bank app you're able to send money through with Contacts and it doesn't go anywhere. Tested it with $1 and didn't go to either party that was present.
#### __Evidence__ 
Can be tested with $1 (Also could be the fact we didn't exchange the exact routing number)
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Eddie Russo
**Coordinates** | vector3(265.4532, -637.7811, 42.01989)
**Steam ID** | steam:11000010b0b0a55
**Discord ID** | discord:154619574153641984
**Citizen ID** | ILT88962
**Character Name** | Eddie Russo

**Comment by Dimmies** [comment]
The transfer via bank number is a unfinished mechanic. Forgot to remove it
