### ISSUE TITLE
Lockpicks dont break?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#458]
#### __Description__ 
You never lose your lockpicks wheter it be lockingpicking a car, ignition or a house, thought you would lose one everytime.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | SnackyJax
**Coordinates** | vector3(108.9581, -1466.807, 28.48258)
**Steam ID** | steam:1100001125cc52d
**Discord ID** | discord:189621397897740288
**Citizen ID** | NOL74308
**Character Name** | Jax Lagusa

**Comment by Dimmies** [comment]
They do, it's just a random chance if you fail.
