### ISSUE TITLE
Weird script 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#459]
#### __Description__ 
There are almost 2 full lines of strange scipt across the top of my screen. Most of them are triangles with question marks.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | buster96u
**Coordinates** | vector3(280.2818, -645.8093, 42.0151)
**Steam ID** | steam:110000109542ea6
**Discord ID** | discord:330570283457183744
**Citizen ID** | PZE32797
**Character Name** | David Wallace

**Comment by Dimmies** [comment]
This is a known issue - as of now I haven't been able to find a fix for this, but a quick game restart usually fixes this. I'm actively looking for a solution and will update when I have more info!
