### ISSUE TITLE
MDT mugshots aren't saving

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#46]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(318.234, -271.5343, 53.91068)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
https://i.imgur.com/fEKrbGw.png

**Comment by Dimmies** [comment]
MDT is also inserting multiple duplicates
+

**Comment by Dimmies** [comment]
Should be fixed. Made the `player_mdt` char_id use unique key and fixed mugshots not saving/loading
