### ISSUE TITLE
Repair Kits

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#461]
#### __Description__ 
Neither of the repair kits are working. The animation is played, the vehicle moved a bit and the kit was used but no repair made.
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2602314286
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(293.1853, -345.3503, 45.00598)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Related to #419
