### ISSUE TITLE
random emotes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#463]
#### __Description__ 
character is using "wait" emote without pressing any keybinds. i placed a bug report a couple days ago about what i think sparked this issue
#### __Evidence__ 
https://streamable.com/c49v7o
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Bandiiit
**Coordinates** | vector3(458.4064, -993.1426, 34.97172)
**Steam ID** | steam:110000119a8c31a
**Discord ID** | discord:330777829161566210
**Citizen ID** | LDW19949
**Character Name** | Dante Stryker

**Comment by Dimmies** [comment]
Merge to #437
