### ISSUE TITLE
PDM Vehicles

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#465]
#### __Description__ 
PDM vehicles spawned in the ground
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Swavy Abe
**Coordinates** | vector3(-1490.647, -822.0066, 23.4375)
**Steam ID** | steam:110000107a92b1c
**Discord ID** | discord:132086949002346496
**Citizen ID** | RYP60154
**Character Name** | Ahmed Camel

**Comment by zeuzible** [comment]
Can confirm I have experienced this as well (after the hotfix) and entering into the PDM catalog and exiting seems to pop the cars back up above the ground where they should be.
