### ISSUE TITLE
inventory and phone

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#467]
#### __Description__ 
can't open inventory f2 and can use my phone
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | bladeofkaos
**Coordinates** | vector3(321.5546, -583.1308, 43.28404)
**Steam ID** | steam:110000106278822
**Discord ID** | discord:213013928287010826
**Citizen ID** | NAZ93868
**Character Name** | Jake Jones

**Comment by Dimmies** [comment]
This seems to be caused by the server thinking you're dead for some reason.
