### ISSUE TITLE
Pillbox Hill Garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#47]
#### __Description__ 
This may be happening with other garages too, but when I spawn my compact, the wheels pop and there is a red message on the top right that says "Engine Stalled".
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(215.5108, -797.0493, 30.82179)
Steam ID | steam:1100001116d7bcc
Discord ID | discord:360933761849884674
Citizen ID | DGF77077

**Comment by Dimmies** [comment]
Couldn't get this to happen. I think it has something to do with the saved health of the vehicle, but it should be updating when it's stored IF it was repaired.

**Comment by Dimmies** [comment]
Every time I've pulled out my compact, it's dropped engine health, sitting at 44% after like 7 times I've brought it out.

**Comment by Dimmies** [comment]
Haven't had any other reports of this and haven't experienced it myself. My guess is the vehicle was stored when it was destroyed and it was spawning destroyed (as intended)
