### ISSUE TITLE
Refueling leading to car breaking down

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#470]
#### __Description__ 
Second time I've refueled at this spot causing my vehicle to instantly break down. Nothing in F8
#### __Evidence__ 
https://i.imgur.com/pFLpwyr.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(263.4833, -1270.752, 29.14841)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by PyotrPalach** [comment]
We had a Sheriff Vehicle breakdown there as well while we were getting the Motorcade ready. Same pump at the same spot
