### ISSUE TITLE
Slots at casino

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#472]
#### __Description__ 
Woman sat down to play the slots, somehow scuffed trying to stand up and was stuck in position, i attempted to sit in different slots and it wouldnt let me. nothing in the f8 menu

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | iTzHoBBs
**Coordinates** | vector3(971.8322, 52.31275, 74.4762)
**Steam ID** | steam:110000103ebb8a4
**Discord ID** | discord:386139575782998017
**Citizen ID** | WQM70520
**Character Name** | Martin Riggs

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
