### ISSUE TITLE
towing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#474]
#### __Description__ 
went to tow a car and nothing happened. car stayed on the ground
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(253.1142, -569.8582, 43.2697)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by SilverTwist86** [comment]
![Screenshot_144](https://user-images.githubusercontent.com/90808095/133530670-0a596efe-9d05-4ce4-a5c0-a557b46a1e3e.png)

**Comment by Dimmies** [comment]
The spike strips error is unrelated.

**Comment by SilverTwist86** [comment]
That's the error that it gave when I tried to tow. I went and test towed another car just fine. This happens time to time.

**Comment by Dimmies** [comment]
Related to #419
