### ISSUE TITLE
Cuffing and Being downed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#475]
#### __Description__ 
I was tazed then cuffed. none of the cops had keys... we manually rp'd the situation. once they aquired tools to but through my cuffs I logged back in. Same as before when i was downed. I cant access my inventory. tried getting knocked out and still no luck.

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | deshwow1987
**Coordinates** | vector3(312.8924, -592.2399, 43.28408)
**Steam ID** | steam:110000119d44fd9
**Discord ID** | discord:220035270089637892
**Citizen ID** | HEA80326
**Character Name** | Ronald Phara

**Comment by Dimmies** [comment]
This is more of a suggestion than a bug.
