### ISSUE TITLE
Lost all ammo 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#476]
#### __Description__ 
Bought a gun, filled with 100 bullets, went to sleep, woke back up and all the ammo is out of the gun and gone.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NKdot
**Coordinates** | vector3(-1094.98, -1658.001, 7.350261)
**Steam ID** | steam:110000116fa27a7
**Discord ID** | discord:299479366973259776
**Citizen ID** | SYY77988
**Character Name** | Luca Montana

**Comment by Dimmies** [comment]
I've updated how weapon ammo saves. This should hopefully resolve this issue, if not, feel free to open another bug report.

Thanks!
