### ISSUE TITLE
cant  open up stash and  f2 inv 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#477]
#### __Description__ 
i grind to 1k plastic butlles and i  put them in my  apartment stash and i left my apartment an i try to open up f2 inventory and it wudnt same whit stash in  my apartment
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Aleks
**Coordinates** | vector3(134.7429, -654.8767, -56.97389)
**Steam ID** | steam:11000013f780e0d
**Discord ID** | discord:843604213144748062
**Citizen ID** | EWX44691
**Character Name** | Alex Mohorko

**Comment by Dimmies** [comment]
Unable to replicate this, but it's a common occurrence. Needs more info
