### ISSUE TITLE
respawn

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#479]
#### __Description__ 
i was in the mines to see how it worked i placed a dynimite to see what happens and i got blown up with it the timer has gone and i cant hold e to respawn 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TheBadGuy
**Coordinates** | vector3(-536.0196, 1943.763, 125.7967)
**Steam ID** | steam:11000010b339ff6
**Discord ID** | discord:431958633656483840
**Citizen ID** | EIB50113
**Character Name** | Prince Devitt

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
