### ISSUE TITLE
Pillbox Hill Garage Addon Notes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#48]
#### __Description__ 
Every time I've pulled out my compact, it's dropped engine health, sitting at 44% after like 7 times I've brought it out.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(216.668, -811.2773, 30.69228)
Steam ID | steam:1100001116d7bcc
Discord ID | discord:360933761849884674
Citizen ID | DGF77077

**Comment by Dimmies** [comment]
Merged with #47
