### ISSUE TITLE
Vehicle Driving HUD

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#49]
#### __Description__ 
Speed Limiter is still titled "Cruise" on the bottom left HUD when driving.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(53.04955, -1355.921, 28.98876)
Steam ID | steam:1100001116d7bcc
Discord ID | discord:360933761849884674
Citizen ID | DGF77077

**Comment by Dimmies** [comment]
Small issue, probably wont worry about this until later

**Comment by Dimmies** [comment]
Added with `pre-alpha-1.12.0`
