### ISSUE TITLE
EYES

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#490]
#### __Description__ 
Whenusing my eyes I'm unable to click on the option highlighted
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TeeShawt
**Coordinates** | vector3(-952.7631, -847.2964, 15.77694)
**Steam ID** | steam:1100001173b1918
**Discord ID** | discord:139866575758032896
**Citizen ID** | XCC81265
**Character Name** | Kevin Spreewell

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
