### ISSUE TITLE
Big smoke hates me

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#491]
#### __Description__ 
Managed to bug him out by requesting another job while I already have a job.
He gets lost in the sauce and doesnt wanna give me a new one no matter what I try.
#### __Evidence__ 
https://medal.tv/clips/65159864/d1337zd9I0XE?invite=cr-MSxBWEssMjI3NDQ3NDEs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(1746.095, 2480.216, 45.74067)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | LWT55589
**Character Name** | Chad Frick

**Comment by Dimmies** [comment]
There is a cooldown for Big Smoke jobs. This is what you're noticing.
