### ISSUE TITLE
i am down and dont know what is going on 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#493]
#### __Description__ 
i fly in and i am down 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | devondavis603
**Coordinates** | vector3(427.8794, -984.3503, 30.7118)
**Steam ID** | steam:11000014149ad24
**Discord ID** | discord:721358892331827280
**Citizen ID** | FYN39195
**Character Name** | Harry Davis

**Comment by Dimmies** [comment]
If you leave while you are dead, you come back dead. You'll need to call a medic.
