### ISSUE TITLE
Hard stuck at blast mines

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#494]
#### __Description__ 
If you use ragdoll (U) after placing explosive, you bug out the explosive and the next time you try to put one on it freezes you in place and doesn't let you go.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(-548.3184, 1896.008, 123.191)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | LWT55589
**Character Name** | Chad Frick

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
