### ISSUE TITLE
Using items even when I cancel the process

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#495]
#### __Description__ 
When I cancel Armor or Bandages / Percs it still uses them but doesn't give me the effects :/
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | @jace
**Coordinates** | vector3(-609.366, -1057.469, 21.40744)
**Steam ID** | steam:11000014a3b4b1a
**Discord ID** | discord:885058533907906580
**Citizen ID** | SKC08130
**Character Name** | Draco Qutorian

**Comment by jace** [comment]
Wrong person?
