### ISSUE TITLE
Tire Nutz Tow Truck Guy

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#50]
#### __Description__ 
You can see the "E" text/hud whilst inside the Tire Nutz building, not sure if that's fixable. I put a screenshot link below.
#### __Evidence__ 
https://gyazo.com/23a08481ed08a182cc31b82e1de0414c
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(-76.45211, -1324.468, 29.26823)
Steam ID | steam:1100001116d7bcc
Discord ID | discord:360933761849884674
Citizen ID | DGF77077

**Comment by Dimmies** [comment]
This isn't fixable
