### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by skydd187** [TheHiveRP/HiveIssues#500]
**Describe the bug**

i quit the game while in pdm, reconnected, and spawned in a garage interior under legion square with no way to get out

**To Reproduce**
1. f8 quit while looking at catalog in pdm
2. reconnect and select last location as spawn
3. spawn in garage interior

**Expected behavior**
i expected to spawn in pdm not the garage

**Screenshots**
https://imgur.com/a/pEWqXJw

**Comment by Dimmies** [comment]
The garage your in is used to display the vehicles. When you enter the catalog, it sets your players location to that garage, so you were actually in that garage when you left. You can contact an Admin+ when you are back in the server and they can TP you out if you're not already out.
