### ISSUE TITLE
Respawned in the hospital bed but can't get out of bed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#509]
#### __Description__ 
Respawned in the hospital bed but can't get out of it. Camera is facing the wall and unwilling to look around. Emotes work but that's it
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TeeShawt
**Coordinates** | vector3(313.9297, -579.0438, 44.20395)
**Steam ID** | steam:1100001173b1918
**Discord ID** | discord:139866575758032896
**Citizen ID** | EPF96063
**Character Name** | Rodney Stevenson

**Comment by Dimmies** [comment]
Pressing E will usually fix this
