### ISSUE TITLE
Prepare Meth Bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#51]
#### __Description__ 
Sometimes when you prepare meth it instantly give you a meth baggie instead of doing the full animation
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(1988.423, 4958.69, 31.35526)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Duplicate of #79
