### ISSUE TITLE
casino wheel crashing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#512]
#### __Description__ 
spinning the wheel caused 3 of us to crash with no crash message. i tried after i got back in and crashed again. and also someone else tried and it crashed us both again
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(973.7717, 44.20314, 74.47627)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by Dimmies** [comment]
Unable to replicate at all.
