### ISSUE TITLE
Interior Customization doesn't save

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#515]
#### __Description__ 
The dashboard color of the Couqette D10 always reverts back to the original color when taking it out of the garage
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | sensu
**Coordinates** | vector3(199.2627, -816.1898, 30.25905)
**Steam ID** | steam:11000010b3c8d3b
**Discord ID** | discord:854934815816024086
**Citizen ID** | IQR64353
**Character Name** | Kai Jung

**Comment by Dimmies** [comment]
#### __Description__ 
The vehicle interior color is not staying and resorts to the default color when retrieved from the garage after being put up or when logging into the server.  Specifically happening to my Windsor drop top.  Interior color change is $500 every change to get it back to the color you want.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ronnie Gurthman
**Coordinates** | vector3(-1731.582, -1055.092, 1.246688)
**Steam ID** | steam:11000010766b926
**Discord ID** | discord:473296664371658752
**Citizen ID** | PVC91827
**Character Name** | Damian Carter
