### ISSUE TITLE
Prop stuck in hand.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#517]
#### __Description__ 
After doing Cop Beacon the little red beacon thing appears to be stuck in your right hand even after doing cancel emote and another prop emote.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JohnnyCache
**Coordinates** | vector3(442.7047, -981.9267, 30.68958)
**Steam ID** | steam:1100001034cbff2
**Discord ID** | discord:101373597708210176
**Citizen ID** | GJI09983
**Character Name** | John Pascallio

**Comment by zeuzible** [comment]
There is a slight easy workaround for this via doing the same emote once more will normally get the prop unstuck from your hand.
