### ISSUE TITLE
INTERIOR COLOR NOT STAYING

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#519]
#### __Description__ 
The vehicle interior color is not staying and resorts to the default color when retrieved from the garage after being put up or when logging into the server.  Specifically happening to my Windsor drop top.  Interior color change is $500 every change to get it back to the color you want.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ronnie Gurthman
**Coordinates** | vector3(-1731.582, -1055.092, 1.246688)
**Steam ID** | steam:11000010766b926
**Discord ID** | discord:473296664371658752
**Citizen ID** | PVC91827
**Character Name** | Damian Carter

**Comment by Dimmies** [comment]
Merging with #515
