### ISSUE TITLE
Give item command weapons error

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#52]
#### __Description__ 
https://i.imgur.com/fLmP6Jv.png
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(-1554.413, -1247.863, 1.604455)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
