### ISSUE TITLE
Random Death

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#524]
#### __Description__ 
Just random death, this costed me cash once.
#### __Evidence__ 
https://medal.tv/clips/65529957/d1337LI3h87F?invite=cr-MSxwM2QsODkxODY3NSw=
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Jackal Kin
**Coordinates** | vector3(-762.5011, -930.618, 17.46179)
**Steam ID** | steam:110000104471e28
**Discord ID** | discord:290516918300049408
**Citizen ID** | PZF51909
**Character Name** | Jackal Roten

**Comment by Dimmies** [comment]
I can't seem to replicate this, but this has happened a few times.

For anyone who has had this issue:
- We're you bleeding?
- Did you use a bandage before dying?
- Did you use Percocets before dying?
- Were you in the water before dying?
- Did you eat/drink before dying?
