### ISSUE TITLE
Phone is stuck in hand?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#529]
#### __Description__ 
My cellphone is stuck in my hand, I don't really know how to fix that. So sorry!
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Anjie
**Coordinates** | vector3(301.3127, -596.8621, 43.2841)
**Steam ID** | steam:1100001074928e6
**Discord ID** | discord:262828827049197568
**Citizen ID** | XOP16572
**Character Name** | Vivienne Lefevre

**Comment by Dimmies** [comment]
I've added a `/propfix` that should fix objects getting stuck in your hands
