### ISSUE TITLE
Inventory splits stacks of items in half

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#532]
#### __Description__ 
On occassion the inventory starts splitting the stacks of items in half when you try to drag them to a different spot in your inventory, put them in a trunk or on the ground. It doesn't matter what number of items you try to transfer. 

When it is an odd number of items it will take half + 1. 
- 21 will split in 11 and 10
- 20 will split in 10 and 10

I have not found an error or any indication in the F8 Console. I did find a different error in the F8 menu regarding the Outlaw Alert script but I doubt this has anything to do with this.

I did one time manage to fix this bug by switching outfits but unfortunately that didn't work this time. As of this moment only thing that works is relogging.
#### __Evidence__ 
https://medal.tv/clips/4rdl24tm7d_3R/GDwu5UMdgsZY?invite=cr-MSxHYXIsMTgzOTE3MjYs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Broebie
**Coordinates** | vector3(-294.3978, -762.9205, 33.96861)
**Steam ID** | steam:110000104bebb76
**Discord ID** | discord:232902749677813760
**Citizen ID** | AFN97107
**Character Name** | Tony Johansson

**Comment by Dimmies** [comment]
This was more than likely caused by your client thinking your control key is down. I've added extra checks to resolve this.

Thanks for the informative report!
