### ISSUE TITLE
robbing houses 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#534]
#### __Description__ 
when you click to search an area it disappears and you get stuck inside the house 

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | photog0510
**Coordinates** | vector3(503.957, -1698.565, -12.92104)
**Steam ID** | steam:11000013e0a6e14
**Discord ID** | discord:521065052904882189
**Citizen ID** | HAI99607
**Character Name** | Dan Davis

**Comment by Dimmies** [comment]
#### __Description__ 
I had 2 different occasions this happened on. First time I broke into a house, and once i tried to access one of the "Search" options it instantly vanished, and so did every other prompt within the house, I tried exiting but that prompt was gone to which resulted in me being stuck inside of this house robbery. The second time, I did the exact same thing, however this time it let me access one of the Search options, but after that one it just repeated the last event and I was stuck in here without any possible prompts again.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | sensu
**Coordinates** | vector3(256.7244, -1680.183, -13.05052)
**Steam ID** | steam:11000010b3c8d3b
**Discord ID** | discord:854934815816024086
**Citizen ID** | IQR64353
**Character Name** | Kai Jung
