### ISSUE TITLE
F1+F2

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#540]
#### __Description__ 
When combined it will cause the F1 wheel to stay on your screen meaning you have to restart the game.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JohnnyCache
**Coordinates** | vector3(428.23, -984.2804, 30.71181)
**Steam ID** | steam:1100001034cbff2
**Discord ID** | discord:101373597708210176
**Citizen ID** | GJI09983
**Character Name** | John Pascallio

**Comment by Dimmies** [comment]
F8 > uirestart fixes this
