### ISSUE TITLE
getting in trunk

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#545]
#### __Description__ 
getting in the trunk is broken. you dont get in the trunk you just hover behind it
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(-82.54585, -1327.827, 29.27248)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by Dimmies** [comment]
#### __Description__ 
Getting into the trunk makes you just stand in the trunk and can't get out without begin carried
#### __Evidence__ 
no f8, cant clip but 2 hours in twitch.tv/GhostieBoi97 stream
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Buddha
**Coordinates** | vector3(-1072.585, -1281.025, 5.97488)
**Steam ID** | steam:110000116dc7db7
**Discord ID** | discord:304578653667459073
**Citizen ID** | LEP29163
**Character Name** | Laroi Padrino
