### ISSUE TITLE
Bikes Spawning While Playing Slots

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#546]
#### __Description__ 
I've had it happen twice now. Idk if its just a certain trigger with the slots that make them spawn or whatever, but they spawn on top of me while playing slots. I've put pictures of the bikes in both moments in RP Media. One spawned INSIDE the slot, the other on top of my head and fell behind me.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Lilium Blake
**Coordinates** | vector3(986.3172, 46.01028, 74.22613)
**Steam ID** | steam:110000106788414
**Discord ID** | discord:237064178156699648
**Citizen ID** | HOJ93511
**Character Name** | Lexi Vilkas

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
