### ISSUE TITLE
Escort distance is too far

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#548]
#### __Description__ 
As title described, when you escort someone with f1, they are attached way too far out
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(80.0578, -1391.302, 29.37614)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment]
Escort is intended to be like this, dragging is what you're looking for
