### ISSUE TITLE
whered my shoes go?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#549]
#### __Description__ 
When I rob someone's shoes, I dont actually get their shoes.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(80.0578, -1391.302, 29.37614)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment]
intended, but this feature has been added
