### ISSUE TITLE
Truck is Stalled/Stuck on Something

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#559]
#### __Description__ 
While I was on a truck delivery (handy jobs) and I had to slow down for a vehicle and when I tried to accelerate I hit an invisble object. As part, I tried to backup, but the vehicle is stalled and won't operate. 
#### __Evidence__ 
I have the screenshot if needed (Discord: Jeifel #9872) for exact location. There were no erros on f8 console
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | jeifel
**Coordinates** | vector3(426.1927, -1991.204, 23.22784)
**Steam ID** | steam:11000013c1c9b5f
**Discord ID** | discord:281518900414251008
**Citizen ID** | TNH13104
**Character Name** | Vinnie Premo

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
