### ISSUE TITLE
Fishing rod update

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#56]
#### __Description__ 
ran through some bushes and rod disappered however I am unable to act aggressive or take other action just as if I still has the rod in my hands.

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-401.19, -406.2492, 32.03886)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | KJI03426
**Character Name** | Dick Mungus

**Comment by Dimmies** [comment]
Merged with #53
