### ISSUE TITLE
Blackjack issue.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#560]
#### __Description__ 
If a player gets blackjack IE Ace+10/King/Queen/Jack the game doesnt payout 3-1 its a standard win for example a 500 bet and the player get Blackjack they should get 1500 but they only get 1000.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JohnnyCache
**Coordinates** | vector3(1023.041, 62.91317, 72.4762)
**Steam ID** | steam:1100001034cbff2
**Discord ID** | discord:101373597708210176
**Citizen ID** | GJI09983
**Character Name** | John Pascallio

**Comment by Dimmies** [comment]
We do this to match our economy.
