### ISSUE TITLE
Harvesting weed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#563]
#### __Description__ 
You have 2 stacks of baggies. One stack has 1 baggy and the other has 99. If the single baggy is in front of the 99, it believes I only have one and will fail to harvest.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(276.656, -646.048, 42.01859)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment]
This is how our inventory currently works. We'll eventually fix it but it's low on the priority list as you can fix it by just stacking the bags.

I'll close this as it's already on the todo list.
