### ISSUE TITLE
Shared apartments

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#564]
#### __Description__ 
Bug where people are sharing apartments again
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Olivia
**Coordinates** | vector3(-527.4092, -653.7844, -56.92728)
**Steam ID** | steam:11000010f2a4e53
**Discord ID** | discord:789384110878490624
**Citizen ID** | ZLM77356
**Character Name** | Lexi Law

**Comment by Dimmies** [comment]
Duplicate of #562
