### ISSUE TITLE
Tattoo Placement / Eddie Russo / Administries#0001

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#565]
#### __Description__ 
Some tattoos are placed too far down or up from their original spots. On the back "Tooth" or the Shark fin, then the Ride Or Die on the Right Arm is too low
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Administries
**Coordinates** | vector3(2731.687, 4701.563, 43.91156)
**Steam ID** | steam:11000010b0b0a55
**Discord ID** | discord:154619574153641984
**Citizen ID** | ILT88962
**Character Name** | Eddie Russo

**Comment by Dimmies** [comment]
Tattoos are placed via a global category offset. Meaning all Torso tattoos (for example) are placed based off of one offset. These will probably stay how they are, some may look weird but for the majority it works as intended. There's probably no fixing this as of now.
