### ISSUE TITLE
Armor gone changing clothes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#566]
#### __Description__ 
was changing clothes, saved outfit, then hit save and as i left the store it took my armor away
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chenneth
**Coordinates** | vector3(-1194.242, -299.3909, 37.84745)
**Steam ID** | steam:11000010a313c85
**Discord ID** | discord:107694309620334592
**Citizen ID** | FYB49811
**Character Name** | Butch Maddox

**Comment by Dimmies** [comment]
This is caused when you change your ped model.
