### ISSUE TITLE
ring doorbell function

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#568]
#### __Description__ 
Numbers don't match. ie: 12115 = 2115

When beeped in, you animate like youre going in but you don't teleport
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(277.3956, -642.5504, 42.01864)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment]
The apartment ID uses the last 4 of those numbers no matter what (aka it's intended)

The teleporting has been fixed
