### ISSUE TITLE
Weed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#57]
#### __Description__ 
Not really a bug but came across my mind while playing around with the weed... I've noticed you can only plant inside a bought house that is purchased by you.. you can't plant inside the apartments you spawn with also can't plant outside. May need a way for people that don't own a house to be able to plant.. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(-54.21255, -1783.423, 0.5997686)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | YSG61543
**Character Name** | Denzel Bobby

**Comment by Dimmies** [comment]
This might be resolved, I added some calls to allow planting/growing while in your apartment.. I think

**Comment by Dimmies** [comment]
Tested by Brody and I, seems to be working.
