### ISSUE TITLE
normal voice range is too far

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#576]
#### __Description__ 
It carries from integrity to pillbox lobby
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(326.6155, -579.5001, 43.2841)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | VAH56855
**Character Name** | Jason Blunt

**Comment by Dimmies** [comment]
I believe this is something to do with the integrity interior. It doesn't happen anywhere else.
