### ISSUE TITLE
Fishing?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#577]
#### __Description__ 
Keeps saying line snapped?
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JJ.
**Coordinates** | vector3(-1869.36, -1222.003, 13.01702)
**Steam ID** | steam:1100001175b134f
**Discord ID** | discord:480404296442183681
**Citizen ID** | CKB39921
**Character Name** | Jax Johnson

**Comment by Dimmies** [comment]
You need to wait for the fish to bite, you'll see a progress bar show
