### ISSUE TITLE
Closed Smoke on the water accessible from outside

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#578]
#### __Description__ 
Title
#### __Evidence__ 
https://i.imgur.com/x7ixxfl.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(-1173.57, -1572.042, 4.663934)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment]
This is currently intended.
