### ISSUE TITLE
Phone Call while shooting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#581]
#### __Description__ 
It will make your gun get put away constantly even if you don't answer the phone, it just ringing was causing my gun to be put away after firing 2 shots.
#### __Evidence__ 
n/a
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | gorilla
**Coordinates** | vector3(239.2397, -605.3216, 41.68016)
**Steam ID** | steam:11000010629d02f
**Discord ID** | discord:140626284471517184
**Citizen ID** | JKK26604
**Character Name** | Jericho Jones

**Comment by Dimmies** [comment]
This isn't related to phone calls, I believe this happens the first time you unholster your weapon? Currently needs more info
