### ISSUE TITLE
Stretchers going under ambulances when put in the back

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#589]
#### __Description__ 
Yesterday the screenshot happend and the same thing happened today on a call. A stretcher was pulled out and when put into the back and the ambulance started moving the scene on the screenshot happened
#### __Evidence__ 
https://i.imgur.com/nG3pzTp.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(315.9519, -575.4912, 43.2841)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by Dimmies** [comment]
![image](https://user-images.githubusercontent.com/28818644/134989940-c60de227-9167-45ee-8bd7-482ee056a7c4.png)
https://cdn.discordapp.com/attachments/891819277382983700/891819497772699758/FiveM_2021-09-26_08-51-15_Trim.mp4
https://cdn.discordapp.com/attachments/891819277382983700/891819502138949662/FiveM_9_26_2021_4_51_24_AM.png
