### ISSUE TITLE
Invisible garage outside prison

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#590]
#### __Description__ 
There seem to be an invisible garage spot outside prison, not sure if intended but it does not show up on the map.
#### __Evidence__ 
https://i.imgur.com/HlsEPPS.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Louie
**Coordinates** | vector3(1867.184, 2595.866, 45.67247)
**Steam ID** | steam:11000010376d6f7
**Discord ID** | discord:254188195263152129
**Citizen ID** | JTU79937
**Character Name** | Alfredo Rossi

**Comment by Dimmies** [comment]
This is intended
