### ISSUE TITLE
No apartments showing up in doorbell function

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#597]
#### __Description__ 
As title suggests
#### __Evidence__ 
https://i.imgur.com/cIy3ynY.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(274.4428, -639.4337, 42.01864)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment]
You have to go into the owners button
