### ISSUE TITLE
Not allowed to play roulette

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#598]
#### __Description__ 
Not able to select the spots I want
#### __Evidence__ 
https://medal.tv/clips/66203222/d1337iahJalm?invite=cr-MSxBeWQsMjI3NDQ3NDEs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(278.4467, -646.533, 42.01859)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment]
This likely has to do with your Mouse Input Method setting. 

Try:
1. Got to GTA Settings
2. Go to Keyboard/Mouse
3. Change Mouse Input Method to Raw Input
