### ISSUE TITLE
Ped Waking Up At Half Health

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#605]
#### __Description__ 
Every time I wake up as a ped, I am at 50% health. I go RP out something, go to sleep full health and then wake up at 50% again.
#### __Evidence__ 
N/A
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TheSingleWhiteFemale
**Coordinates** | vector3(279.3865, -639.5376, 42.01861)
**Steam ID** | steam:11000013e8ef1f6
**Discord ID** | discord:612143178316775426
**Citizen ID** | FZA06960
**Character Name** | Annabelle Shaw

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
