### ISSUE TITLE
Getting in trunk results in ped standing.

### ISSUE THREAD

**Issue by eamundson1** [TheHiveRP/HiveIssues#606]
**Describe the bug**
Was watching a stream an observed that getting in trunk results in ped standing. Both top and bottom are exposed outside the trunk.
![standing](https://user-images.githubusercontent.com/89711562/135184445-09f7f3da-e958-4bf5-b25b-2794713c872d.JPG)

**Screenshots**
If applicable, add screenshots to help explain your problem as well as help find the cause/solution. This includes screenshots of your F8 console.

**Additional context**

**Comment by Dimmies** [comment]
Duplicate of #488
