### ISSUE TITLE
Arg Danny face!

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#607]
#### __Description__ 
this is the second day in a row I have come on the server with instant dannyface. which kinda wigs me out, I have tried a lot to fix it. But it doesn't tend to work. I am trying to figure out if it's my set face not saving, me loading in to quickly or if its fiveM being fiveM.
#### __Evidence__ 
I aint got it.. sorry....
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Sayahchan
**Coordinates** | vector3(300.8892, -598.5759, 43.71267)
**Steam ID** | steam:11000010413aae1
**Discord ID** | discord:397959613061791745
**Citizen ID** | FFU45850
**Character Name** | Charlene Garcia

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
