### ISSUE TITLE
Jumbo Shake

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#609]
#### __Description__ 
I got a Jumbo Shake from a house robbery, and when I went to drink it it gave no food or water
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JiglyBits
**Coordinates** | vector3(-626.5909, 6254.911, 2.736221)
**Steam ID** | steam:110000104880fac
**Discord ID** | discord:344338909439721472
**Citizen ID** | DRA39719
**Character Name** | Joe Jenkins

**Comment by Dimmies** [comment]
This report has had no additional info, can't be replicate and no one else has reported a similar issue.

This report will be closed, if anyone else experiences this issue, please open a new ticket.
