### ISSUE TITLE
Ammunation broken

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#610]
#### __Description__ 
Trying to purchase a gun, have enough money, but the gun just makes a noise when i try to buy it
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Quacky
**Coordinates** | vector3(22.07656, -1106.767, 29.79702)
**Steam ID** | steam:1100001098aad13
**Discord ID** | discord:211251873573896192
**Citizen ID** | TRO92911
**Character Name** | Devon Winchester

**Comment by Dimmies** [comment]
This is likely caused by having 0 or more than 1 in the move amount.
