### ISSUE TITLE
MDT Mugshot not always loading

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#611]
#### __Description__ 
Profile pictures on MDT disappear on most people, some it sticks.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Swavy Abe
**Coordinates** | vector3(-525.7197, -1024.167, 22.86897)
**Steam ID** | steam:110000107a92b1c
**Discord ID** | discord:132086949002346496
**Citizen ID** | RYP60154
**Character Name** | Ahmed Camel

**Comment by Dimmies** [comment]
This is caused by image links being dead. This is not really an issue with the MDT.
