### ISSUE TITLE
Armor Issues

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#613]
#### __Description__ 
2 days ago I applied armor to my ped which gave me 75% armor, I haven't lost any armor since then so I thought it saving it in the database and me having it when I reentered the city was pretty cool. But yesterday I lost all of my armor but when I got back on after 3am today I was back full health and my armor was back at 75% which it shouldn't have been
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Molicheu
**Coordinates** | vector3(235.6523, -754.0727, 30.82619)
**Steam ID** | steam:1100001369b056b
**Discord ID** | discord:424257715439927296
**Citizen ID** | XVC80994
**Character Name** | Kody Scott

**Comment by Dimmies** [comment]
#### __Description__ 
I was shot and downed last night, got treated and stayed downstairs before last nights reset. Got onto server, spent about 2 hours dicking around, looked down, and I have full Armor already. I never rebought the armor or put on armor, it just showed up
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(441.6593, -984.5618, 34.97029)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach
