### ISSUE TITLE
Ads and Twitter UI stack on each other sometimes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#615]
#### __Description__ 
Phone shows ads on top of twitter
#### __Evidence__ 
https://ibb.co/y0qc4R4
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Olivia
**Coordinates** | vector3(2669.489, 2744.065, 38.33242)
**Steam ID** | steam:11000010f2a4e53
**Discord ID** | discord:789384110878490624
**Citizen ID** | ZLM77356
**Character Name** | Lexi Law

**Comment by Dimmies** [comment]
#### __Description__ 
After opening yellow page i went to tweeter and now i see both app together.
#### __Evidence__ 
https://cdn.discordapp.com/attachments/709783994677329921/899581129982627860/unknown.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Grumpy Panda
**Coordinates** | vector3(-1174.154, -1581.665, 4.331796)
**Steam ID** | steam:1100001361b9d6d
**Discord ID** | discord:398117627442233346
**Citizen ID** | KCL77910
**Character Name** | James Famingo
