### ISSUE TITLE
personal vehicle disapears when you logout or crash

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#62]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(2949.574, 2785.047, 40.55437)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
I restarted hive-misc and it seemed to remove all of Brody's vehicles AND Codys vehicle. (I was standing at PDM and Cody was at Bennys) Maybe this has something to do with it? 

Could also be completely unrelated as no ones vehicles gets deleted when they're driving, near it, looking at it, etc.

**Comment by Dimmies** [comment]
Should be fixed with the vehicle persistence script
