### ISSUE TITLE
I am not getting RC car on wheel

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#621]
#### __Description__ 
for a few weeks now I have not been getting the RC car on the wheel when i hit mystery gift. this has happen 5 times now 3 of them today
#### __Evidence__ 
https://medal.tv/clips/66560124/d1337wtyEcvV?invite=cr-MSx0ek8sMjI3ODkwMTMs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pawbles
**Coordinates** | vector3(968.1776, 40.83508, 74.87696)
**Steam ID** | steam:110000109b9ed84
**Discord ID** | discord:93034243633995776
**Citizen ID** | PFF14507
**Character Name** | Saoirse OTool

**Comment by Dimmies** [comment]
The mystery prize has a small chance of giving a RC Car, every other time it's money.
