### ISSUE TITLE
Bank overlay sticks

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#622]
#### __Description__ 
If you press escape after a transaction too soon the bank UI will stick until you open it again and close it. ui restart doesn't work for this.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | D-reck
**Coordinates** | vector3(152.9829, -1029.815, 28.63647)
**Steam ID** | steam:110000104ae2dd0
**Discord ID** | discord:114647394120892424
**Citizen ID** | MZS25831
**Character Name** | Leland James

**Comment by Dimmies** [comment]
`uirestart` in F8 now fixes stuck bank ui
