### ISSUE TITLE
PD Lobby Locks

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#627]
#### __Description__ 
I spawned at MRPD as an officer. I was not sure if I was clocked on duty so I toggled job duty, which ended up being to off duty. After clocking back on duty I could no longer unlock the lobby doors. I was able to get in through the doors off the parking lot however.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | sg4bomb
**Coordinates** | vector3(446.3968, -992.5917, 30.69199)
**Steam ID** | steam:1100001082657d2
**Discord ID** | discord:585216646247874570
**Citizen ID** | VEO84338
**Character Name** | Jeremy Fields

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
