### ISSUE TITLE
texting

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#628]
#### __Description__ 
i can only text one person and can only receive texts from that same person
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Silver_Twist86
**Coordinates** | vector3(-70.87302, -1331.766, 29.25997)
**Steam ID** | steam:110000104ca4df2
**Discord ID** | discord:215280083957448704
**Citizen ID** | JRX14884
**Character Name** | Bryan Stone

**Comment by SilverTwist86** [comment]
![Screenshot_155](https://user-images.githubusercontent.com/90808095/135738310-c754c220-9bd3-4f52-b08e-703538cb8bc9.png)
