### ISSUE TITLE
Selfies Not Working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#629]
#### __Description__ 
When you take a selfie on twitter, the image is blacked out
#### __Evidence__ 
https://imgur.com/Eybal8J
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Chuff
**Coordinates** | vector3(-83.68799, -1327.625, 29.25111)
**Steam ID** | steam:110000101c301ed
**Discord ID** | discord:147386472016642058
**Citizen ID** | FHO94294
**Character Name** | Tommy Jenkins

**Comment by Dimmies** [comment]
This is unfortunately a known bug that is out of my hands at the moment. Restarting FiveM seems to be the temp. fix.
