### ISSUE TITLE
House Stash

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#63]
#### __Description__ 
Stash is not shared for all people for a singular house. Each person has a unique stash within a home. My items stored in my house are only visible to me, Cody's items stashed in my house are only visible to him, Tupa's Items are only visible to Tupa. In theory, lets say you have a gang of 10 people, each person could have a 1,000 lb stash in the same home, making that house have 10,000 lb stash
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(1301.886, -570.8976, 71.58172)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Brody and I tested this, found no issues. Might need to try and reproduce this?

**Comment by Dimmies** [comment]
This is believed to be associated with #22
