### ISSUE TITLE
Hair/ Clothing Bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#630]
#### __Description__ 
When I press cnacel in the clothing store or in the apartment in the clothing menu it changes my hair back to the one it was before. There are no errors in the F8.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | pink11
**Coordinates** | vector3(424.6592, -805.6065, 29.49115)
**Steam ID** | steam:11000010ec9a291
**Discord ID** | discord:608502932480196618
**Citizen ID** | UBB71788
**Character Name** | Baily Fields

**Comment by Dimmies** [comment]
Next update should have a possible fix for this?
