### ISSUE TITLE
House robbery

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#634]
#### __Description__ 
cops respond to a house robbery the house was empty and un robbed but the door was unlocked cops sat outside and watched the door and after 10 mins door was still unlocked i went back 25 mins later and its still unlocked after 45 mins we can still go in and it still allows the house to be robbed
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | ItzAreezz
**Coordinates** | vector3(137.0873, -1413.758, 28.98022)
**Steam ID** | steam:110000115a618c6
**Discord ID** | discord:213861073332338688
**Citizen ID** | WQF28932
**Character Name** | Lamar Abercrombie

**Comment by eamundson1** [comment]
This isn't necessarily a bug. It makes sense to leave the house if the alarm goes off and come back later once the cops leave or just leave entirely. The cops can wait and watch the house and jump them when they re-enter. So it gives both sides a chance.
He said it was power gaming but the same could be said if the crims  aren't allowed to attempt their tactics by altering game mechanics. 
Maybe make so it, after a certain amount of time, the cops can relock the house.

**Comment by Dimmies** [comment]
Houses automatically relock after some time.
