### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#638]
#### __Description__ 
Can't receive or send text messages, Not sure what is causing this issue.
#### __Evidence__ 
https://i.imgur.com/KP0HlGo.png
https://i.imgur.com/b6bNjax.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | MZRY
**Coordinates** | vector3(-62.06684, -1331.126, 29.26831)
**Steam ID** | steam:11000011391cb2d
**Discord ID** | discord:155484627946045440
**Citizen ID** | KOR49407
**Character Name** | Nathan Mort

**Comment by Dimmies** [comment]
This hasn't been reported or update in quite some time, nor am I able to replicate. If this issue persists, please open another report.
