### ISSUE TITLE
gta being gta

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#639]
#### __Description__ 
livery replaced with grass texture
#### __Evidence__ 
https://gyazo.com/42cb6724932e689984e171757a92ddaf
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Quacky
**Coordinates** | vector3(-1019.638, -1106.305, 1.592499)
**Steam ID** | steam:1100001098aad13
**Discord ID** | discord:211251873573896192
**Citizen ID** | ECG30259
**Character Name** | Jackson Camorra

**Comment by Dimmies** [comment]
1. Go to GTA Settings
2. Go to Advanced Graphics
3. Restore Defaults

If restoring Advanced Graphics back to defaults doesn't work, try resetting your graphics settings to default.
