### ISSUE TITLE
HUD doesn't unhide when you select a character

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#64]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(1274.464, -1712.595, 54.7715)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Just removed the toggling of the HUD for now, the HUD will show when in the character selection screen but fuccc it
