### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#640]
#### __Description__ 
I was shot and downed last night, got treated and stayed downstairs before last nights reset. Got onto server, spent about 2 hours dicking around, looked down, and I have full Armor already. I never rebought the armor or put on armor, it just showed up
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(441.6593, -984.5618, 34.97029)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Merged to #613
