### ISSUE TITLE
Saved outfits partially gone

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#641]
#### __Description__ 
Saved some outfits at the clothing store and used while on server. Logged out and logged back in and the character is wearing only partial outfit. Went to wardrobe and aselected outfit and save, however it does not change. also notice the apartment is being shared by someone else and has pot plants I didn't plant. The apt 17341. No error code.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-135.5504, -653.0723, -56.97388)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by eamundson1** [comment]
Also the character had a different face when I first logged on.

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
