### ISSUE TITLE
Bike poofed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#645]
#### __Description__ 
I had to relog to fix my phone and when I logged back in my bike poofed 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | SniperEvolving
**Coordinates** | vector3(-48.80924, -1116.761, 26.43537)
**Steam ID** | steam:110000108f231ca
**Discord ID** | discord:118549893038997506
**Citizen ID** | MOF09179
**Character Name** | Evo Thompson

**Comment by Dimmies** [comment]
Merged with #360
