### ISSUE TITLE
Car vanished at postal

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#647]
#### __Description__ 
I parked my car near the postal place, and i picked up the job overthere. when i finished the postal route i came back to the postal and my car was no longer there. looked at my phone and tried to gps mark it but its not marking the vehicle. i went to the garage and its telling me its outside. i went to the impound lot and i have no vehicles in there.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TTV/Skywolfieee
**Coordinates** | vector3(-212.627, -1161.719, 23.16379)
**Steam ID** | steam:1100001034ad670
**Discord ID** | discord:114666562438299651
**Citizen ID** | UKX40861
**Character Name** | Memphis Raines

**Comment by Dimmies** [comment]
Merged with #360
