### ISSUE TITLE
Vehical Despawned

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#649]
#### __Description__ 
My motorcycle despawned and when I added the waypoint on my phone app, it says that it marked the location but nothing comes up on the map so I have no clue how to find it
#### __Evidence__ 
https://i.imgur.com/hve5Mcw.jpeg https://i.imgur.com/rwXiI2C.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Mr_B_G
**Coordinates** | vector3(1518.462, -2048.631, 76.89854)
**Steam ID** | steam:11000013eadaf56
**Discord ID** | discord:488390960426778644
**Citizen ID** | JUT08982
**Character Name** | Sean Taylor

**Comment by Dimmies** [comment]
Merged with #360
