### ISSUE TITLE
Ceramic Pistol Crafting isn't working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#65]
#### __Description__ 
This could be because of the issue with the slots being in the wrong order (AKA this might already be fixed)
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(1344.921, -552.2168, 46.19065)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
