### ISSUE TITLE
Ammo

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#658]
#### __Description__ 
When using ammo to reload a weapon, you reload, but the ammo does not get used in your inventory. Someone brought it up, I got one set of pistol ammo, and was able to reload my handgun 3 times without it being consumed in inventory. Going to check for shotgun and rifle
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(462.2201, -998.9481, 30.68959)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
#### __Description__ 
Issue also occurs with Shotgun and Rifle Ammo
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(485.2753, -1007.467, 30.70555)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach
