### ISSUE TITLE
MDT Messes with Radar in Car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#665]
#### __Description__ 
Pulling up the MDT while in a patrol vehicle with the radar enabled will either shut down the radar entirely or shut down the front antenna.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(1803.077, 3567.942, 35.2196)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
This is likely a conflict with your controls

You can change these controls in Settings > Key Bindings > FiveM
