### ISSUE TITLE
Crafting Table didn't show the Slide-In Interact

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#67]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(116.4734, -188.9903, 53.96901)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Caused by #64
