### ISSUE TITLE
Missing car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#672]
#### __Description__ 
Car wont show up on phone app says waypoint set but no waypoint is showing up.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | TheVanillaGorilla89
**Coordinates** | vector3(814.5757, -1470.387, 26.83188)
**Steam ID** | steam:11000013fbef10b
**Discord ID** | discord:682007977950969876
**Citizen ID** | XDL67461
**Character Name** | Drew Down

**Comment by Dimmies** [comment]
Merged with #360
