### ISSUE TITLE
THE RAPTURE 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#675]
#### __Description__ 
i see a white light when dr.garcia try to take a cop down stairs y i was in the surgery fixing my face 
#### __Evidence__ 
https://imgur.com/WA04fDW
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | WrittenEternity
**Coordinates** | vector3(326.1356, -573.5324, 43.2841)
**Steam ID** | steam:110000104af99d2
**Discord ID** | discord:90645817605492736
**Citizen ID** | MDW14173
**Character Name** | Sleepy Brown

**Comment by Dimmies** [comment]
This is due to your visual mods. (Usually caused by NVE)
