### ISSUE TITLE
MDT

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#683]
#### __Description__ 
was checking a plate showed as noone owned it but someone looked it up and said it came back as someone 
#### __Evidence__ 
https://i.imgur.com/aIxzhaj.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | kristafire9178.ttv
**Coordinates** | vector3(433.3399, -992.5036, 30.68958)
**Steam ID** | steam:11000013e8e86cc
**Discord ID** | discord:484116967943438339
**Citizen ID** | XZO91089
**Character Name** | Sakura Fujii

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
