### ISSUE TITLE
Ammo Repo

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#688]
#### __Description__ 
When equipping a PD Glock as a non-sheriff character it wipes your ammo. Was this intenional or nah? I've lost 2 full stacks because I didn't know what caused then the second time I realized it 

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Administries
**Coordinates** | vector3(-957.3886, -326.8327, 37.92035)
**Steam ID** | steam:11000010b0b0a55
**Discord ID** | discord:154619574153641984
**Citizen ID** | ILT88962
**Character Name** | Eddie Russo

**Comment by Dimmies** [comment]
Duplicate of #646
