### ISSUE TITLE
Police Armory isn't working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#69]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(481.3992, -997.3911, 30.68979)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Probably the nightstick

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
