### ISSUE TITLE
Lungs icon pops up when fishing

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#693]
#### __Description__ 
When casting to fish, the Lungs Icon on the HUD pops up and fills about 1/5th of the way full. I haven't seen lungs for anything else, don't think its intended. Thanks!
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | OhNoItsEdge
**Coordinates** | vector3(-1728.431, -1057.333, 1.26371)
**Steam ID** | steam:110000106bb70ad
**Discord ID** | discord:229992982093365248
**Citizen ID** | RUM31342
**Character Name** | James Edge

**Comment by Dimmies** [comment]
The lungs hud shows whenever any part of your body is in water. This is intended :)
