### ISSUE TITLE
Contacts Issue

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#697]
#### __Description__ 
Suggested Contacts are not saving. Tried multiple times with different people.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | NadeFrame
**Coordinates** | vector3(1762.05, 2483.607, 45.7407)
**Steam ID** | steam:110000110adcb80
**Discord ID** | discord:262487501434912768
**Citizen ID** | QPY65340
**Character Name** | Drake Carter

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
