### ISSUE TITLE
Face

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#698]
#### __Description__ 
MY RJ character has a different face than he should. No error code.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-467.921, -655.295, -56.97388)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by eamundson1** [comment]
JR I meant

**Comment by eamundson1** [comment]
Face reverted after relogging.

**Comment by Dimmies** [comment]
Related to #607
