### ISSUE TITLE
Roulette Improvements

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#7]
#### __Description__ 
The "Game Starting Soon" countdown is tilted, untilt it. Also maybe add last win to the UI.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(1033.104, 59.35011, 72.4761)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
> The "Game Starting Soon" countdown is tilted, untilt it
Done as of `pre-alpha-1.12.0`
