### ISSUE TITLE
Towed Vehicles 'Rubberbanding'

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#70]
#### __Description__ 
Can probably attach the vehicle to the tow truck instead of the bone
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(404.4822, -1632.697, 30.79925)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
