### ISSUE TITLE
Elevator not working [BUG] 

### ISSUE THREAD

**Issue by Dopykoh** [TheHiveRP/HiveIssues#701]
**Describe the bug**
When you spawn in the apartment, leave it and you want to go back in you cant. It wont show anything at all. No prompt at all.

**To Reproduce**
1. Go to apartments and log out to get a spawn in the apartment.
2. Log back on to server.
3. Spawn on the character. 
4. Leave the apartment. Try to go back in and you wont be able to.

**Expected behavior**
Prompt "E to enter apartment"

**Screenshots**
https://i.imgur.com/CJTcIzg.jpeg
NO F8 error in this.

**Additional context**
https://streamable.com/qu21aa

**Comment by Dimmies** [comment]
Can you record a video of you doing this?

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
