### ISSUE TITLE
Evidence Disappeared 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#702]
#### __Description__ 
Just completed a report for Rusty Shackelford, and I placed all of his evidence in the store portion of the report, and it then disappeared. I tried to take a quick nap to see if that fixed it, but it did not. I was able to capture a screenshot of everything we took off of his perso
#### __Evidence__ 
https://i.imgur.com/m9E9MFy.png

#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Mr_B_G
**Coordinates** | vector3(479.9097, -1008.221, 26.2732)
**Steam ID** | steam:11000013eadaf56
**Discord ID** | discord:488390960426778644
**Citizen ID** | SGB07068
**Character Name** | Jay Green

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
