### ISSUE TITLE
Scratchoff Loser when really Winner

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#704]
#### __Description__ 
Ive gotten 2 of the same "winners" with sad face emoji's and when i fully scratched both they said loser.
#### __Evidence__ 
https://i.imgur.com/aBCE1cG.png

https://i.imgur.com/d1SL3zj.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | GHOSTx
**Coordinates** | vector3(39.09659, -1177.725, 29.03963)
**Steam ID** | steam:11000010818c546
**Discord ID** | discord:294166400614793217
**Citizen ID** | AVK11830
**Character Name** | Chris Lawson

**Comment by Dimmies** [comment]
This is intended, sad face = instant lose. I've updated the UI to be more clear :)
