### ISSUE TITLE
Mechanic 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#71]
#### __Description__ 
Need radial button to impound 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | xBrodyxS
**Coordinates** | vector3(410.2906, -1628.877, 29.29195)
**Steam ID** | steam:11000010c834ebf
**Discord ID** | discord:424994252775358465
**Citizen ID** | YSG61543
**Character Name** | Denzel Bobby

**Comment by Dimmies** [comment]
Added with `pre-alpha-1.12.0`
