### ISSUE TITLE
Phone wallpaper missing/notification bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#716]
#### __Description__ 
Just logged in, spawned at MRPD and pulled out my phone and this is what I saw. Phone wallpaper, custom twitter picture are both gone & you see these weird notifications.
#### __Evidence__ 
https://i.imgur.com/7JElwxC.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(461.9939, -990.1704, 30.68987)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | UKD42498
**Character Name** | Adam Hall

**Comment by Dimmies** [comment]
Until this is completely fixed, relogging usually resolves this issue

**Comment by Dimmies** [comment]
Should be fixed since a few updates ago
