### ISSUE TITLE
Add sounds to drilling

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#72]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(-89.36829, -1314.429, 29.30309)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Added with `pre-alpha-1.12.0` along with a few other drilling improvements (better controls, models, etc.)
