### ISSUE TITLE
Unable to unlock own vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#723]
#### __Description__ 
Locked my vehicle while it was out, returned to it and i'm unable to unlock and get into it despite notif telling me it's unlocked. 
#### __Evidence__ 
https://i.ibb.co/6RdRQgP/image.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel
**Coordinates** | vector3(20.58869, -1879.927, 22.92355)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment]
Duplicate of #708
