### ISSUE TITLE
Gas station bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#724]
#### __Description__ 
When you have little amount of money on you and you fill up your car it will fill the car up to the amount of money you have on you but wont take it, but when you fill it up a second time it fills the car up to the amount and takes the money, In the clip I start with 54% gas and $11, after the first fill up it ends at 71% and $11. 
I fill it up again and it ends at 87% gas and took the $11.
#### __Evidence__ 
https://streamable.com/7yg4qm
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | MZRY
**Coordinates** | vector3(14.00446, -1876.594, 22.82596)
**Steam ID** | steam:11000011391cb2d
**Discord ID** | discord:155484627946045440
**Citizen ID** | KOR49407
**Character Name** | Nathan Mort

**Comment by Dimmies** [comment]
Related to #707
