### ISSUE TITLE
24/7 Registers need to alert police

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#73]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(25.85605, -1352.31, 29.33527)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Added this with `pre-alpha-1.12.0` but needs testing
