### ISSUE TITLE
Scuba Gear

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#732]
#### __Description__ 
Scuba gear is no longer working.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Administries
**Coordinates** | vector3(431.6907, -3111.248, -0.09240043)
**Steam ID** | steam:11000010b0b0a55
**Discord ID** | discord:154619574153641984
**Citizen ID** | PPG01078
**Character Name** | Steven Ramirez

**Comment by eamundson1** [comment]
While watching I could see that the ped is using normal breath which depletes slower. The air tank does not have an air reserve.Tupa
