### ISSUE TITLE
Taxi

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#735]
#### __Description__ 
Did not receive any calls for passebgers in a 1hr time.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(140.8505, -3025.257, 7.04089)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
You have to toggle the job on
