### ISSUE TITLE
Car is scuffed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#736]
#### __Description__ 
I can lock and unlock my car. I can even access the trunk but when I try to get in the vehicle it acts like it is locked. Tried going to the garage to see if it scuffed in a way where I could pull another one out but the garage says it is out. Plate is 73KLB084 and is an Ellie. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | WreckedFX
**Coordinates** | vector3(-55.17179, -1113.982, 26.43631)
**Steam ID** | steam:11000010594c796
**Discord ID** | discord:692782998252290051
**Citizen ID** | YXI56665
**Character Name** | Douglas MacDugal

**Comment by WreckedFX** [comment]
![Screenshot (106)](https://user-images.githubusercontent.com/68293780/139372429-425a2c3f-6057-4141-a097-909813e070c8.png)
![Locked out](https://user-images.githubusercontent.com/68293780/139372441-a070e598-681c-4aeb-97bf-81ff19feba13.png)

**Comment by WreckedFX** [comment]
I don't know what I did but I went to grab one of my other vehicles came back and it let me in.

**Comment by Dimmies** [comment]
Related to #593
