### ISSUE TITLE
Inventory/Storage UI Bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#737]
#### __Description__ 
When dragging items in the stash you can drag an item down or right to the edges of the screen.  This will cause your UI to shift out of the view of the screen.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Safefield
**Coordinates** | vector3(-585.4027, -655.0373, -56.97388)
**Steam ID** | steam:110000106d6e53c
**Discord ID** | discord:189895867489189888
**Citizen ID** | ZHD76011
**Character Name** | RJ Safefield

**Comment by Dimmies** [comment]
Just a visual bug
