### ISSUE TITLE
Silent Gunshots

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#738]
#### __Description__ 
No gunshot audio in Casino
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Safefield
**Coordinates** | vector3(973.972, 46.63913, 74.47624)
**Steam ID** | steam:110000106d6e53c
**Discord ID** | discord:189895867489189888
**Citizen ID** | ZHD76011
**Character Name** | RJ Safefield

**Comment by Dimmies** [comment]
Duplicate of #721
