### ISSUE TITLE
Stacking Dropped Items

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#739]
#### __Description__ 
When you drop an item you are no longer able to stack items within that dropped area. Not sure whether intentional to stop duping or whatever but it would be a great QoL Change
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JohnnyCache
**Coordinates** | vector3(2938.828, 2772.223, 39.26385)
**Steam ID** | steam:1100001034cbff2
**Discord ID** | discord:101373597708210176
**Citizen ID** | XQX05491
**Character Name** | Barry Shimshek

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
