### ISSUE TITLE
Everyone is recieving police alerts for some reason?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#74]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(25.85605, -1352.31, 29.33527)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
I believe this is fixed, whenever your job would change, instead of grabbing the new job it would grab the stored job within the client files. Needs testing though

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
