### ISSUE TITLE
interaction menu not appearing for apartments

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#740]
#### __Description__ 
When moving into the elevator for apartment, the (e) for apartments interaction menu does not pop up, pressing e also doesn't bypass and send you to apartment either.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel
**Coordinates** | vector3(284.0783, -653.227, 42.01861)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
