### ISSUE TITLE
Petrol Can Usage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#742]
#### __Description__ 
When fueling a vehicle, when you finish, it consumes the petrol can from your inv
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-1818.933, -2808.274, 13.94427)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
This is intentional with the change of jerry cans some time ago
