### ISSUE TITLE
More Petrol

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#743]
#### __Description__ 
Petrol Can also does not fuel the vehicle when using

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(-1820.165, -2813.029, 13.94428)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | USC02137
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Petrol Cans don't work anymore. You'll have to go to the gas station to buy a jerry can.
