### ISSUE TITLE
Fake Plates bugged

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#745]
#### __Description__ 
Fake Plates don't stick to the vehicle and when you put the vehicle away after applying the plate it goes into the garage but the vehicle with the original plate dupes and goes back to the spot you applied the fake plate.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Administries
**Coordinates** | vector3(114.796, -1948.053, 20.60121)
**Steam ID** | steam:11000010b0b0a55
**Discord ID** | discord:154619574153641984
**Citizen ID** | ILT88962
**Character Name** | Eddie Russo

**Comment by Dimmies** [comment]
Fake plates are intended to not stick
