### ISSUE TITLE
Housing Address

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#746]
#### __Description__ 
In the 'view house' menu of the housing purchase option, it does not display an address in the "address" box.
#### __Evidence__ 
https://i.imgur.com/OAr80Hg.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(76.78524, -1947.66, 21.17414)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
