### ISSUE TITLE
Cannot park car

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#748]
#### __Description__ 
I cannot park my car. Have tried getting in and out and moving on and off the spot
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | StevenBillls
**Coordinates** | vector3(215.4049, -789.6244, 30.40141)
**Steam ID** | steam:11000013bedcecb
**Discord ID** | discord:501585887096864788
**Citizen ID** | PVF94604
**Character Name** | Ricky Barnes

**Comment by Dimmies** [comment]
Duplicate of #419
