### ISSUE TITLE
givecash might not be working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#75]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(152.1672, -1029.723, 28.47638)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Needs confirmation, never had an issue with this.

**Comment by Dimmies** [comment]
Original Issue still unconfirmed

Fixed an issue where sending money to an ID that isn't online takes your money and spits a error in the server console

**Comment by Dimmies** [comment]
Can't replicate
