### ISSUE TITLE
Weird Invisible Vehicle Bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#753]
#### __Description__ 
I'll let the video speak for itself.... lol
#### __Evidence__ 
https://medal.tv/clips/69906711/d1337vTnhhTk?invite=cr-MSwxczIsMjU1MjYxMDYs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(252.0899, -644.7004, 39.88371)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
Seemed to be an issue with our vehicle persistence script. We've since stopped using that script so this shouldn't happen anymore.
