### ISSUE TITLE
Pockets scuffed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#754]
#### __Description__ 
after being killed and revived by EMS my pockets were skuffed and I could not add anything to my inventory or use anything, After relogging I noticed the items that were took for me had re-appeared after logging back into the server, Not sure if this is practical for everyone or just me.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | 123
**Coordinates** | vector3(-466.6869, -655.0756, -56.97388)
**Steam ID** | steam:1100001110310f2
**Discord ID** | discord:483709657794215946
**Citizen ID** | OSM69850
**Character Name** | Twink Carter

**Comment by Dimmies** [comment]
Seems like someone was still in your pockets for some reason.
