### ISSUE TITLE
Cars spawnig in Inetgrity

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#757]
#### __Description__ 
I heard a noise and thought I knew what it was and looked around the attached is what I found.
#### __Evidence__ 
https://steamcommunity.com/sharedfiles/filedetails/?id=2642750773  https://steamcommunity.com/sharedfiles/filedetails/?id=2642751184    https://steamcommunity.com/sharedfiles/filedetails/?id=2642751512  https://steamcommunity.com/sharedfiles/filedetails/?id=2642751745
https://steamcommunity.com/sharedfiles/filedetails/?id=2642751745
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(283.8931, -662.6462, 54.74819)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
This doesn't seem to happen too often anymore as we've moved away from using our vehicle persistence script
