### ISSUE TITLE
F8

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#758]
#### __Description__ 
Everytime I have used F8 in the past 2 days it has hung up my system and required a fiveme restart.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(283.8931, -662.6462, 54.74819)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
This is a CFX/FiveM issue - Unfortunately it can't be resolved on our end.
