### ISSUE TITLE
No twitter photo

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#759]
#### __Description__ 
I posted 3 photos on twitter and they were all black. did not recive any errors.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(283.8931, -662.6462, 54.74819)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by Dimmies** [comment]
Duplicate of #629
