### ISSUE TITLE
Tow Bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#760]
#### __Description__ 
I've noticed i've been having issues with towing local cars in particular. I try getting the keys, moving the vehicles more on the tow bed, and changing which way the car faces. Nothing seems to work.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cloverism
**Coordinates** | vector3(445.4373, -290.4381, 49.22311)
**Steam ID** | steam:1100001082ad5b9
**Discord ID** | discord:520646426951155714
**Citizen ID** | AEF88850
**Character Name** | Margo Gray

**Comment by Dimmies** [comment]
This is what I like to call "Dead Cars" they are cars that just can't be interacted with. I've yet to find a fix for this. See #419 for more info
