### ISSUE TITLE
Randomized Emote Bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#761]
#### __Description__ 
While using /lean, if you pull your gun out it stops the emote.  If you do /lean again, it will lean you with a random prop.  I see myself with a cigarette, while others see me with a beer or a phone.
#### __Evidence__ 
https://clips.twitch.tv/BoldTallNostrilPunchTrees-dv1MtB_YZcDqaYuW
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Safefield
**Coordinates** | vector3(-13.56826, -1855.589, 24.738)
**Steam ID** | steam:110000106d6e53c
**Discord ID** | discord:189895867489189888
**Citizen ID** | ZHD76011
**Character Name** | RJ Safefield

**Comment by Dimmies** [comment]
This is just FiveM/GTA.
Essentially you see one prop, but someone else sees another. I don't believe this is something we can fix on our end.
