### ISSUE TITLE
Stcuk F8 Menu

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#772]
#### __Description__ 
Menu can be opened but cannot close. Must ctrl alt delete to close program. No error
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1413.74, -425.8117, 36.15747)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
F8 menu is embedded into FiveM itself, this is a FiveM/CFX issue.
