### ISSUE TITLE
Same vehicle cannot enter cannot store

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#773]
#### __Description__ 
Cannot enter vehicle and when attempt to storeplate it will not do anything.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1415.147, -428.0259, 36.06565)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
Other person also could not store. Plate 10KXM971. Finally able to store by  /dv while pushing.

**Comment by Dimmies** [comment]
Duplicate of #419
