### ISSUE TITLE
Sentinel Classic Suspension

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#776]
#### __Description__ 
Whenver I try to install the Level 4 Suspension on my Sentinel Classic it does not apply. Even when someone else also trys to put on a suspension kit on the Sentinel Classic.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Tri
**Coordinates** | vector3(132.3524, -3025.86, 7.040891)
**Steam ID** | steam:11000011765f427
**Discord ID** | discord:237350512205365249
**Citizen ID** | LAG88738
**Character Name** | Taichi Ishikari

**Comment by Dimmies** [comment]
From what I've seen, some vehicles don't have a level 4 suspension. I'm not sure if this is a GTA thing, or something with us.
