### ISSUE TITLE
Random emotes

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#779]
#### __Description__ 
When I type lean 5 I get a random lean emote rather than the desired lean emote. This is at Hayes
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1418.257, -437.8065, 35.93542)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Make sure you're not putting a space between lean and 5.

If you're not getting the emote you're intending on getting, it's either not an emote on Hive or a different lean emote.
