### ISSUE TITLE
Handsup sometimes stop you from aiming your gun until you press the keybind again

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#78]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(905.1936, 16.76447, 79.20271)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Could be fixed now, changed it to check if the player is playing the hands up animation instead of checking for the variable.

**Comment by Dimmies** [comment]
Tested and working
Fixed with `pre-alpha-1.12.0`
