### ISSUE TITLE
Cannot get in vehicle

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#780]
#### __Description__ 
After unlocking cannot get in vehicle. This was by Hayes. Margo also had trouble getting in her vehicle yesterday at  Hayes.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-2030.429, -467.6979, 11.39209)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by Dimmies** [comment]
Related to #593
