### ISSUE TITLE
BMX Fuel

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#783]
#### __Description__ 
You can put gas in the BMX bicycle, and the fuel level will also go down as you drive it.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(-78.82787, -1762.094, 29.79491)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
Fuel doesn't effect the bike.
You can fuel it, and fuel will drain, but it won't do anything.
