### ISSUE TITLE
Phone Infinite Incoming Call

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#786]
#### __Description__ 
If you call someone, but then immediately press to stop calling them, it infinitely says "Incoming Call" on the other persons phone until they get another call.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Csylord
**Coordinates** | vector3(-1956.972, 2294.088, 54.90227)
**Steam ID** | steam:1100001131d8e35
**Discord ID** | discord:290174672765583360
**Citizen ID** | WSZ07301
**Character Name** | Benji Yuko

**Comment by Dimmies** [comment]
Until an official fix is put in place for this, if you hit F8 then type `uirestart` it'll remove the Incoming Call UI
