### ISSUE TITLE
Same jacket different patches

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#789]
#### __Description__ 
Picture shows the same jacket but it's different male and females in terms of patches
#### __Evidence__ 
https://i.imgur.com/PmYZuoP.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(308.9746, -590.7594, 43.2841)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by Dimmies** [comment]
You should be able to change these in the decals section in the clothing store
