### ISSUE TITLE
Preparing Meth skips the animation the first time you do it and just gives you meth

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#79]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(-43.20644, -1099.184, 26.42235)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
