### ISSUE TITLE
CAN'T STORE CARS

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#796]
#### __Description__ 
I'm unable to store any of my vehicles.  When I go to my garage, the vehicle I currently have out shows to be in there and retrievable.  Leaving me with a duplicate. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ronnie Gurthman
**Coordinates** | vector3(14.51691, -1870.966, 22.97731)
**Steam ID** | steam:11000010766b926
**Discord ID** | discord:473296664371658752
**Citizen ID** | PVC91827
**Character Name** | Damian Carter

**Comment by Dimmies** [comment]
Duplicate of #419
