### ISSUE TITLE
Remove Tables from PDM

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#80]
#### __Description__ 
Dazzer should have it
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(-40.73315, -1100.735, 26.42235)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
