### ISSUE TITLE
SENTINAL SG4 SPAWNING WITH NO WHEELS OR GLASS

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#800]
#### __Description__ 
When I retrieve my Sentinal SG4 from the garage, it spawns with no wheels, tires, glass, interior, or anything other than the body but it drives and functions.  Also been having a LOT of troubles with the locking mechanism and being able to get into this particular vehicle.  
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ronnie Gurthman
**Coordinates** | vector3(223.2699, -817.8305, 29.98898)
**Steam ID** | steam:11000010766b926
**Discord ID** | discord:473296664371658752
**Citizen ID** | PVC91827
**Character Name** | Damian Carter

**Comment by Dimmies** [comment]
Locking issue is related to #593

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
