### ISSUE TITLE
vehicles flashing inside mrpd garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#802]
#### __Description__ 
There are vehicles that flash in and out inside the garage. Its like someone tried to store them and now they show up randomly and disapear

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(446.6701, -988.393, 25.69997)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | GHH64203
**Character Name** | Mason Saint

**Comment by Dimmies** [comment]
This seemed to be an issue with a vehicle persistence script that we've mostly stopped using
