### ISSUE TITLE
Rims not sticking on Schlagen GT

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#804]
#### __Description__ 
I've been buying the Lozspeed Mk.V (Sport Rims) everyday for my Schlagen GT. Though every time I pull it out of the Garage they are back to stock.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | OhNoItsEdge
**Coordinates** | vector3(-56.75351, -1116.754, 25.7282)
**Steam ID** | steam:110000106bb70ad
**Discord ID** | discord:229992982093365248
**Citizen ID** | RUM31342
**Character Name** | James Edge

**Comment by Dimmies** [comment]
Can't seem to replicate this issue. Hopped on my test server, bought the same car and wheels and was able to store/retrieve vehicle with no issues. Any additional information would be great! :D
https://medal.tv/games/gta-v/clips/4OGLobXeTLiJI/Kz6FvI1MxyO6
