### ISSUE TITLE
Phone issues? maybe

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#810]
#### __Description__ 
Ok so I came down to fish and chips and realized I couldnt hear the music from the dj booth, no big but I went to retweet the tweet that the place was open and was told I could not retweet tweets, then my curor dissapeared and I couldnt navigate my phone to exit twitter, I could only close the phone. So I hit f8 and here is the messages I got. 
#### __Evidence__ 
https://i.imgur.com/gqJA7Hl.jpg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Sayahchan
**Coordinates** | vector3(-380.3428, 279.5681, 84.81506)
**Steam ID** | steam:11000010413aae1
**Discord ID** | discord:397959613061791745
**Citizen ID** | FFU45850
**Character Name** | Charlene Garcia

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
