### ISSUE TITLE
Trucking job tires are spawning popped.

### ISSUE THREAD

**Issue by BlueStorm324** [TheHiveRP/HiveIssues#813]
**Describe the bug**
When you ask for your truck at the trucker job, as you turn the truck on, it spawns with popped tires.

**To Reproduce**
1. Go to the Trucking job
2. Click on the worker to get your truck
3. Scroll down to the need new route
4. See error as the truck spawns.

**Expected behavior**
This problem never occurred before. I expected my tires to be in working condition.

**Comment by bikerider84550** [comment]
I have the same problem with my Dubsta 6x6 that I own , and also with the garbage truck when doing the garbage job and then again when I do the trucking job . It's always the middle set of tires on each one of the trucks .

**Comment by BlueStorm324** [comment]
Yeah, same here. It's always the middle set of tires on each one of the trucks.
