### ISSUE TITLE
semi job tire pop

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#814]
#### __Description__ 
Tires pop automaticly when getting a job for the semi truck
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | pwmderheim
**Coordinates** | vector3(-342.3216, -2699.201, 6.227034)
**Steam ID** | steam:110000145c6aa26
**Discord ID** | discord:418843816494104577
**Citizen ID** | CYO64960
**Character Name** | Toni Paterson

**Comment by bikerider84550** [comment]
I have the same problem with my Dubsta 6x6 that I own , and also with the garbage truck when doing the garbage job and then again when I do the trucking job . It's always the middle set of tires on each one of the trucks .
