### ISSUE TITLE
DUBSTA 6X6 BUG

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#815]
#### __Description__ 
Anytime I retrieve my Dubsta 6x6 from the garage it comes out with the center two tires blown out.  If I repair it at Benny's, with a repair kit, or with an advance repair kit, it briefly puts the tires back on there but they immediately blow up leaving nothing but the rims.  It has done this after 4 resets and several naps
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ronnie Gurthman
**Coordinates** | vector3(-34.7284, -1053.255, 28.25324)
**Steam ID** | steam:11000010766b926
**Discord ID** | discord:473296664371658752
**Citizen ID** | PVC91827
**Character Name** | Damian Carter

**Comment by bikerider84550** [comment]
I have the same problem with my Dubsta 6x6 that I own , and also with the garbage truck when doing the garbage job and then again when I do the trucking job . It's always the middle set of tires on each one of the trucks .
