### ISSUE TITLE
Tires Popping 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#817]
#### __Description__ 
I have a Dubsta 6x6 and both tires on the middle axle popped when i got it out of my garage ,  so I took it to Benny's and fixed it , but the second I started to move they both popped again . I had a mechanic look at it and he repaired it but the same thing happened again . This also happens with 3 axle trucks such as the garbage trucks for the garbage job and also for the trucks supplied for the trucking job . I have pictures I can send and also a video clip but I don't know how to send them from here or who to send them to but do have them to send if somebody can contact me for them . 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Lucifer Diamond
**Coordinates** | vector3(268.4178, -751.107, 30.67494)
**Steam ID** | steam:110000109378804
**Discord ID** | discord:215685525476999168
**Citizen ID** | OTT35295
**Character Name** | Lucifer Diamond

**Comment by bikerider84550** [comment]
![Tires Pop](https://user-images.githubusercontent.com/32671476/141520501-a6f2d701-8324-4736-a182-2cd252afd61d.jpg)
![My Middle Axle Flat Tires](https://user-images.githubusercontent.com/32671476/141520521-d26fbe82-2f24-4e41-8d07-881a9dafda48.jpg)
https://clips.twitch.tv/SpoopyColdbloodedCroquetteBudStar-EYz1MmZRXhZGCt7a

**Comment by bikerider84550** [comment]
![These Tires Popped Too](https://user-images.githubusercontent.com/32671476/141523649-c40b5053-95a7-4f57-8516-682a8eb86bc5.jpg)
