### ISSUE TITLE
Work truck bug

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#823]
#### __Description__ 
tires are popping on work trucks cannot be fixed. Same happens with new trucks that are brought out.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1424.967, -432.8757, 35.86604)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by bikerider84550** [comment]
I have the same problem with my Dubsta 6x6 that I own , and also with the garbage truck when doing the garbage job and then again when I do the trucking job . It's always the middle set of tires on each one of the trucks .

**Comment by eamundson1** [comment]
It is the middle axle on both sides btw. Attempted mechanic fix and admin fix and the tires blow.
