### ISSUE TITLE
Got disconnected from mumble

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#829]
#### __Description__ 
I got disconnected from mumble and needed to take a nap in order to not hot mic
#### __Evidence__ 
https://i.imgur.com/QZMmzpp.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(345.7262, -585.4153, 43.2841)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by Dimmies** [comment]
This seems to be an issue with your internet connection and possibly even an issue with FiveM mumble connection. Unfortunately there's not much we can do to fix it.
