### ISSUE TITLE
24/7 Vault

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#83]
#### __Description__ 
No option to crack the vault
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(483.6312, -997.4115, 30.68979)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | OOE62144
**Character Name** | Jane Doe

**Comment by Dimmies** [comment]
I have no idea what this report means, bug was reported in PD armory?
