### ISSUE TITLE
Not all dials being colored 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#833]
#### __Description__ 
Not all the dials on the Sentinel SG4 changes color unlike on the sultan. Pictures shows the difference
#### __Evidence__ 
https://i.imgur.com/rEknynV.jpeg https://i.imgur.com/Ky77hSo.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(296.5277, -608.1366, 42.63271)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by 350ztuner018** [comment]
Fixed
