### ISSUE TITLE
CAN'T STORE MOTORCYCLE

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#839]
#### __Description__ 
Cannot store my NRG900F motorcycle 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Ronnie Gurthman
**Coordinates** | vector3(2.769851, -1874.974, 23.23699)
**Steam ID** | steam:11000010766b926
**Discord ID** | discord:473296664371658752
**Citizen ID** | PVC91827
**Character Name** | Damian Carter

**Comment by Dimmies** [comment]
Duplicate of #419
