### ISSUE TITLE
Showing ID shows for everyone

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#84]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(-2131.446, 1100.969, -27.36738)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Dimmies** [comment]
Fixed with `pre-alpha-1.12.0`
