### ISSUE TITLE
Phone acting up

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#841]
#### __Description__ 
Nothing opens or works on the phone.
#### __Evidence__ 
https://i.imgur.com/H798VpP.png

https://i.imgur.com/cFxMVMl.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dopykoh.TTV
**Coordinates** | vector3(-1432.182, -453.4186, 36.39251)
**Steam ID** | steam:11000011376e182
**Discord ID** | discord:193681533620584448
**Citizen ID** | JVG00859
**Character Name** | LJ Medina

**Comment by Dimmies** [comment]
This usually happens when you sit at the character selection screen for a while. A relog usually fixes this

**Comment by Dimmies** [comment]
Duplicate of #716
