### ISSUE TITLE
Fishing Pole stuck in hand when you toggle fishing off

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#85]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dimmies
**Coordinates** | vector3(1042.902, -2606.263, 9.517284)
**Steam ID** | steam:11000010690b8fb
**Discord ID** | discord:98162698654605312
**Citizen ID** | LDH52158
**Character Name** | Dimmies Dimbo

**Comment by Lazrik** [comment]
Hi

**Comment by Dimmies** [comment]
Can't seem to replicate the issue

**Comment by Dimmies** [comment]
Fixed in `pre-alpha-1.14.0`
