### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#856]
#### __Description__ 
My inventory is only two blocks wide and its very weird. In the screen shot you can see the 3 blocks wide. my resolution is 1920x1080 and i made a ticket and i got told to made a bug report.
#### __Evidence__ 
https://drive.google.com/file/d/1gy_X0PoAWOaN0noFWQVekmjS8woVv_ZT/view?usp=sharing
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | FZN LINK
**Coordinates** | vector3(2970.292, 2776.299, 38.34279)
**Steam ID** | steam:11000013f8e2b83
**Discord ID** | discord:592420396846940160
**Citizen ID** | DZD60535
**Character Name** | Jordan Hicks

**Comment by Dimmies** [comment]
Check your display settings again, all of your UI looks zoomed in which is caused by your resolution. This is something you'll have to fix on your end.
