### ISSUE TITLE
police garage not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#86]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(430.997, -991.9796, 25.69999)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
This is caused by the vehicles not being in the server atm.
