### ISSUE TITLE
Music stops completely after turning streamer mode back on

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#864]
#### __Description__ 
When streamer mode have been turned on it turns off music entirely from the DJ systems even if you turn it back on 
#### __Evidence__ 
https://i.imgur.com/xHoix80.jpeg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(-381.781, 266.8362, 86.4592)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by Dimmies** [comment]
When turning streamer mode off, you'll have to restart the song for the music to come back on.
