### ISSUE TITLE
Ped Characters

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#866]
#### __Description__ 
Ped Characters spawn as half health
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(-348.7622, -654.8075, -56.92728)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | AUM87461
**Character Name** | Shanice Robinson

**Comment by Dimmies** [comment]
Duplicate of #605
