### ISSUE TITLE
meth not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#87]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(2017.619, 4972.229, 41.36758)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Can't replicate, seems to be working for me

**Comment by Dimmies** [comment]
Fixed in `pre-alpha-1.13.0`
