### ISSUE TITLE
Impound/tow not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#873]
#### __Description__ 
Unable to impound vehicles and cannot tow motorcycles.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(-1419.144, -447.7291, 35.90969)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | EZB40406
**Character Name** | Edward Robideaux

**Comment by eamundson1** [comment]
Did not work for margo either

**Comment by eamundson1** [comment]
Cars cannot be impounded either by mechanic menu or at impound yard.

**Comment by Dimmies** [comment]
Related to #419
