### ISSUE TITLE
Can't impound

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#875]
#### __Description__ 
Unable to impound at impound lot and using a "local tow" in our mechanic's toolbox. Shows as complete, but car doesn't poof.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cloverism
**Coordinates** | vector3(259.1364, -629.8328, 41.19566)
**Steam ID** | steam:1100001082ad5b9
**Discord ID** | discord:520646426951155714
**Citizen ID** | AEF88850
**Character Name** | Margo Gray

**Comment by Dimmies** [comment]
Related to #419
