### ISSUE TITLE
Vehicle duped

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#877]
#### __Description__ 
I was not at Hayes but I left my vehicle there for like 10 mins or more. I returned and my vehicle didnt poof. However when attempting to store in garage it wasnt storing so I decided to check my garage and realized that I had it in my garage already.
#### __Evidence__ 
https://medal.tv/games/gta-v/clips/72540416/d1337ytiznv1?invite=cr-MSxiWFgsOTAxOTE5Niw
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dopykoh.TTV
**Coordinates** | vector3(-2028.558, -465.1488, 11.44783)
**Steam ID** | steam:11000011376e182
**Discord ID** | discord:193681533620584448
**Citizen ID** | VJG97234
**Character Name** | Jose Fernandez

**Comment by Dimmies** [comment]
Related to #419
