### ISSUE TITLE
all addon cars not spawning

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#88]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(197.6411, -826.4597, 30.29815)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Known - Waiting on Jaysome
