### ISSUE TITLE
Dynamite in ammunition store?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#880]
#### __Description__ 
Dynamite without a license unless that is intended. Seems weird I can purchase an explosive
#### __Evidence__ 
https://prnt.sc/20q27rv
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Plague Doctor Grimm
**Coordinates** | vector3(19.80511, -1107.753, 29.79702)
**Steam ID** | steam:110000106173c7a
**Discord ID** | discord:138010052937121792
**Citizen ID** | MUT57085
**Character Name** | Oliver LeBlanc

**Comment by Dimmies** [comment]
This is intended as it's part of the mining job.
