### ISSUE TITLE
Furniture will not place properly

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#882]
#### __Description__ 
No matter what I do, I cannot place furniture down it follows my cursor everywhere.. and I cannot change any settings to fix it. I have also opened a ticket about it.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Sayahchan
**Coordinates** | vector3(1389.919, -569.135, 51.94659)
**Steam ID** | steam:11000010413aae1
**Discord ID** | discord:397959613061791745
**Citizen ID** | FFU45850
**Character Name** | Charlene Garcia

**Comment by Dimmies** [comment]
Fix:

`GTA Settings > Keyboard / Mouse` - Set `Mouse Input Method` to `Raw Input`
