### ISSUE TITLE
Phone bug.

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#884]
#### __Description__ 
Unable to read my messages on the phone at all.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | JohnnyCache
**Coordinates** | vector3(1758.625, 2485.057, 45.24157)
**Steam ID** | steam:1100001034cbff2
**Discord ID** | discord:101373597708210176
**Citizen ID** | XQX05491
**Character Name** | Barry Shimshek

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
