### ISSUE TITLE
pRISION tAKING iTEMS

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#889]
#### __Description__ 
Prison is taking various, random items such as ID, DL, miner hat, pickaxe, food, etc..
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | max_jaeger
**Coordinates** | vector3(1714.261, 2511.785, 45.56486)
**Steam ID** | steam:110000104c03932
**Discord ID** | discord:235560868597858311
**Citizen ID** | ZSQ25714
**Character Name** | Jonathaon Ignacious-Rutherford

**Comment by eamundson1** [comment]
Items reappeared some time latter.

**Comment by Dimmies** [comment]
Duplicate of #859
