### ISSUE TITLE
safes are not working in liquor stores

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#89]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-44.05296, -1753.979, 29.44145)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Can't replicate 
![image](https://user-images.githubusercontent.com/28818644/127775165-a5f7319f-a798-4828-b09b-e2e3f98bdd84.png)

**Comment by Dimmies** [comment]
Fixed in `pre-alpha-1.13.0`
