### ISSUE TITLE
No Messages

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#894]
#### __Description__ 
When I go to my phone and open up messages, it's empty. Also, when someone messages me I get the notification but when I open it up nothing is there.  
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Molicheu
**Coordinates** | vector3(1432.506, 3627.266, 7.912304)
**Steam ID** | steam:1100001369b056b
**Discord ID** | discord:424257715439927296
**Citizen ID** | XVC80994
**Character Name** | Kody Scott

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
