### ISSUE TITLE
Trash eats up items?

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#898]
#### __Description__ 
I put a weed seed into the dumpster to hand it off to someone, all sneaky like ya know? But when the buyer went to look into the bin- nothing was there! What on earth?
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Anjie
**Coordinates** | vector3(-1438.304, -453.5189, 35.26281)
**Steam ID** | steam:1100001074928e6
**Discord ID** | discord:262828827049197568
**Citizen ID** | RML13468
**Character Name** | Khalia Hawthorne

**Comment by Dimmies** [comment]
Dumpsters currently go off of location, best bet is to drive away from the area (far enough to lose line of sight to the dumpster) then come back, that should reset the dumpster location thus returning your items.

Added this to the todo list, dumpster will get a rewrite in the future.
