### ISSUE TITLE
Car changed plates

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#899]
#### __Description__ 
I've tuned my car to all lvl 4's, then put about 20k worth of cosmetics to it, I decided to get some stuff changed to it in the morning. I went down to the Tuner shop to change out my lights, after the changed the lights then got out of the car my car went back to stock and my plates changed, the guys there said they saw me driving in as a stock car but thats not how it looked in my eyes. Now when I try to put it in the garage it says the car isn't mines, but on my app it says my car is still out. The car is a Deluxo GT
#### __Evidence__ 
https://i.imgur.com/kBo5hpD.jpg
https://i.imgur.com/7gPHC7R.jpg
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Molicheu
**Coordinates** | vector3(-87.94762, -1991.883, 18.01696)
**Steam ID** | steam:1100001369b056b
**Discord ID** | discord:424257715439927296
**Citizen ID** | XVC80994
**Character Name** | Kody Scott

**Comment by Dimmies** [comment]
Related to #419
