### ISSUE TITLE
Fingerprint ID scanning isn't working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#9]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
https://i.imgur.com/0judSvJ.png
#### __Additional Information__
Title | Information
------------ | -------------
Coordinates | vector3(473.4833, -1009.354, 26.27346)
Steam ID | steam:11000010690b8fb
Discord ID | discord:98162698654605312
Citizen ID | LDH52158

**Comment by Dimmies** [comment]
The creation of the fingerids are storing it in the the metadata, but the scanning is getting it from the fingerid slot

**Comment by Dimmies** [comment]
Remove the fingerprint search
Maybe add having to be put in the system before you can search

**Comment by Dimmies** [comment]
Should be fixed.

* Fingerprint Evidence now uses metadata fingerprints
* Fingerprint scanning in PD now uses metadata fingerprints
* All fingerprints should match now
* Removed fingerprint searching since it's too easy to just search up a fingerprint and find a match
