### ISSUE TITLE
laptops at arcade not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#90]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(2736.419, -381.2788, -48.39503)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Seems like it works, but it's a little touchy, have to look at the right spot.

**Comment by Dimmies** [comment]
Changed the model, it's still kinda touchy, but it's a little easier to access (just eye on the touchpad)
