### ISSUE TITLE
I can't move furniture without moving my cam/character

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#901]
#### __Description__ 
I'm sure this is how the UI is supposed to function but it makes it EXTREMELY hard to put furniture exactly where i want it and decorate without things being in the floor or hovering. Please change this. 
#### __Evidence__ 
https://ibb.co/JBN7QX5
https://ibb.co/M5SrR3R
https://ibb.co/LrFx3ym
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel
**Coordinates** | vector3(4.247466, -1889.015, -4.149128)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment]
1. Got to GTA Settings
2. Go to Keyboard/Mouse
3. Change Mouse Input Method to Raw Input
