### ISSUE TITLE
Lost $ at Wheel

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#903]
#### __Description__ 
I had $500 taken from me for the wheel and the wheel proceeded to not spin. Just wanted to let yall know this is still goin on.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cloverism
**Coordinates** | vector3(975.7344, 49.7906, 74.68111)
**Steam ID** | steam:1100001082ad5b9
**Discord ID** | discord:520646426951155714
**Citizen ID** | AEF88850
**Character Name** | Margo Gray

**Comment by Dimmies** [comment]
Related to #619
