### ISSUE TITLE
/seat doesn't work

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#905]
#### __Description__ 
when sitting in seat i am unable to move to /seat1 or /seat2 tried in 4 door vehicles and was unable to  move to those or /seat3 /seat4. 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel
**Coordinates** | vector3(-1815.55, -533.6656, 30.10368)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment]
You'll need to put a space between the command and the seat id

ex: /seat 1
