### ISSUE TITLE
when editing objects, it creates duplicates

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#906]
#### __Description__ 
title is self explanatory. 
#### __Evidence__ 
https://i.ibb.co/Qk0Q9xM/image.png
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel
**Coordinates** | vector3(0.9941121, -1889.435, -4.128873)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
