### ISSUE TITLE
Missing Neon, neon headlights, and rims after storm (reset)

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#909]
#### __Description__ 
After the storm i logged back on and noticed i was missing what i described in the title. I parked my car in the garage before hand to avoid this but the issue still happened.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Britamins
**Coordinates** | vector3(-362.7271, -124.8181, 38.69593)
**Steam ID** | steam:110000133272d55
**Discord ID** | discord:156579090315345920
**Citizen ID** | MHP48555
**Character Name** | Briten Clark

**Comment by Dimmies** [comment]
Related to #419
