### ISSUE TITLE
Stash

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#91]
#### __Description__ 
After using my stash in my house, the stash now says I cant access (No inventory spaces and not showing current inventory). Cody Couldnt see it either after use. No f8 errors, leaving and coming back in did not fix it. Cody also placed something in my stash and it disappeared
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(1302.23, -572.5671, 49.18233)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Can't seem to replicate the issue
