### ISSUE TITLE
Police Lockers Sound

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#914]
#### __Description__ 
Police lockers (and probably assuming EMS lockers) do not have the new stash sound effects
#### __Evidence__ 
n/a
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuz
**Coordinates** | vector3(248.3652, -647.4512, 39.08738)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | UKD42498
**Character Name** | Adam Hall

**Comment by Dimmies** [comment]
This is intended atm
