### ISSUE TITLE
Growing Weed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#92]
#### __Description__ 
When planting weed plants, the planters stack on top of one another for each plant. Some have 2, some have 3, and all will flash every now and then to show 1. happens for all strains

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(1297.992, -573.0938, 49.18233)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
![image](https://user-images.githubusercontent.com/28818644/128044193-11a9db6b-f0f8-4354-a4fa-47b7d9091ac2.png)

**Comment by Dimmies** [comment]
This seems to fix if you reenter the house

**Comment by Dimmies** [comment]
Fixed in `pre-alpha-1.14.0`

ALSO

Added Max Weed plant count
