### ISSUE TITLE
Handcuffed

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#93]
#### __Description__ 
You can enter and exit a home while Handcuffed

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(1301.605, -571.3536, 71.59619)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Moved to Trello
