### ISSUE TITLE
Home Key Count

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#937]
#### __Description__ 
Count of homebutton is incorrect.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | hnt-neptunium
**Coordinates** | vector3(442.7374, -990.2628, 34.97025)
**Steam ID** | steam:1100001441b0eb2
**Discord ID** | discord:333624300042977280
**Citizen ID** | BRJ62199
**Character Name** | Douth Chaney

**Comment by ghost** [comment]
This can be closed, resolved in next update.
