### ISSUE TITLE
Weed plants spawn on top of the apartment interior

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#94]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-1288.062, -431.2552, 6.227467)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
They stayed but they were invisible, I just not spawning the objects

**Comment by Dimmies** [comment]
Note: This also only happens in Apartments

**Comment by Dimmies** [comment]
Can't seem to replicate the issue

**Comment by Dimmies** [comment]
This seems to be something to do with it trying to be placed on the ground but it being placed on the roof of the apartment instead : https://i.imgur.com/fBlVanq.png

**Comment by Dimmies** [comment]
Seems to be fixed with new apartment interior
