### ISSUE TITLE
Car spawned without body parts and rims. 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#941]
#### __Description__ 
After the storm I went to pull my SG4 out of the garage and it spawned with no wheels just brakes, and the spoiler and bumpers were set to stock, i still had underglow and paint though.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Britamins
**Coordinates** | vector3(128.9403, -1716.229, 28.72386)
**Steam ID** | steam:110000133272d55
**Discord ID** | discord:156579090315345920
**Citizen ID** | MHP48555
**Character Name** | Briten Clark

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
