### ISSUE TITLE
Pulled out vehicle, lost all mods and upgrades

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#942]
#### __Description__ 
I pulled out my winky license plate 59LSV480, and it didn't station me in the vehicle. Looked behind me and saw it was pulled out but missing all mods and upgrades done to it. It wouldn't start or move. I don't want to store it or move it incase it stays like this. The attached picture is what it looks like right now.
#### __Evidence__ 
https://cdn.discordapp.com/attachments/916853433921830972/916853652096966687/unknown.png

#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | optimuskel
**Coordinates** | vector3(240.386, -805.1664, 30.32615)
**Steam ID** | steam:110000113ae38ab
**Discord ID** | discord:373132494264074240
**Citizen ID** | SFN81264
**Character Name** | Olive Fontaine

**Comment by Dimmies** [comment]
Related to #419
