### ISSUE TITLE
arcade laptops still not working. They do look better doh

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#95]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(2736.982, -380.118, -48.39496)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Confirmed working with Cody, just have to look in a certain spot
