### ISSUE TITLE
inventory not working 

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#96]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(-786.7626, -1508.188, 1.591416)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Fixed in `pre-alpha-1.14.0`
