### ISSUE TITLE
Only one injured person at a time in a helicopter

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#965]
#### __Description__ 
I just had an incident where I could only put one downed individual into the swift. Had to "stabilize" the two others before I could get them in
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(316.5607, -592.0966, 43.28406)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by 350ztuner018** [comment]
I dont see a EMS swift anywhere

**Comment by Dimmies** [comment]
> I dont see a EMS swift anywhere

It's `ambuchopper`
