### ISSUE TITLE
opening shops not working (E) button

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#97]
#### __Description__ 
NO DESCRIPTION
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Cody
**Coordinates** | vector3(374.2785, 326.5267, 103.5664)
**Steam ID** | steam:11000010079352b
**Discord ID** | discord:216718685883203584
**Citizen ID** | IEO17773
**Character Name** | Cody Ohana

**Comment by Dimmies** [comment]
Issue comes from #96
