### ISSUE TITLE
Gun and Taser Shooting Randomly

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#971]
#### __Description__ 
My gun and taser both fire nonstop randomly and i cant stop it 
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | StevenBillls
**Coordinates** | vector3(322.439, -277.5018, 53.91122)
**Steam ID** | steam:11000013bedcecb
**Discord ID** | discord:501585887096864788
**Citizen ID** | VGU97571
**Character Name** | Johnny Lawson

**Comment by Dimmies** [comment]
Unable to replicate this issue

Check your macros, game keybinds etc.

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
