### ISSUE TITLE
Casino Garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#974]
#### __Description__ 
You can pull cars out at the casino, but cannot store cars there.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | zeuzible
**Coordinates** | vector3(896.6277, -18.60852, 78.57985)
**Steam ID** | steam:11000010c3171fa
**Discord ID** | discord:234874168607375361
**Citizen ID** | BFV40301
**Character Name** | Andre Turner

**Comment by Dimmies** [comment]
This is intentional
