### ISSUE TITLE
Cars pulled from garage

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#976]
#### __Description__ 
Cars are having their tires pop and they are barely damaged as theyre being pulled from garage.
#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dopykoh.TTV
**Coordinates** | vector3(-2024.643, -472.5435, 11.01243)
**Steam ID** | steam:11000011376e182
**Discord ID** | discord:193681533620584448
**Citizen ID** | VJG97234
**Character Name** | Jose Fernandez

**Comment by Dimmies** [comment]
https://medal.tv/games/gta-v/clips/74965785/d13370AqKc3F?invite=cr-MSw3WGgsMTMzNzM1ODQs
