### ISSUE TITLE
Inventory Issue

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#98]
#### __Description__ 
I think someone mentioned it today, could have been Cody. Cant access inventory, cant access shops or stashes becasue they link to inventory, and cant use the /giveitem function

#### __Evidence__ 
NO EVIDENCE
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Pyotr Palach
**Coordinates** | vector3(49.04366, -1352.104, 29.29152)
**Steam ID** | steam:11000011b56c5c4
**Discord ID** | discord:612497931169169408
**Citizen ID** | DXN74618
**Character Name** | Pyotr Palach

**Comment by Dimmies** [comment]
Duplicate of #96
