### ISSUE TITLE
Refueling not working

### ISSUE THREAD

**Issue by TheHiveRP** [TheHiveRP/HiveIssues#983]
#### __Description__ 
Tried multiple times as shown to refuel a vehicle, but was unable to
#### __Evidence__ 
https://medal.tv/games/gta-v/clips/74971421/d1337cLXDyEV?invite=cr-MSxaN0MsMjQ5MDczMTgs
#### __Additional Information__
Title | Information
------------ | -------------
**Steam Name** | Dirgia
**Coordinates** | vector3(307.2661, -589.5147, 43.28408)
**Steam ID** | steam:110000103f9c1d5
**Discord ID** | discord:194461233410211840
**Citizen ID** | FEC98698
**Character Name** | Karen Rainer

**Comment by Dimmies** [comment]
Hasn't been reported since, nor am I able to replicate. If this issue persists, please open another report.
